puppetlabs/puppetlabs-puppet_agent

- .travis.yml
- Gemfile
Remove unused `development` Gems, and unnecessary variables for `rake
test` setup in Travis.
> (maint) Simplify test configuration

- README.markdown
@MikaelSmith , I would love to get you to review this. Thanks!
> DOC-2036: review and edit README for puppet_agent

- README.markdown
README TOC wasn't updated for prior documentation changes, update it to
include new sections.
> (docs) Update Table of Contents

- spec/acceptance/class_spec.rb
- spec/spec_helper_acceptance.rb
Add acceptance tests confirming that the agent works after upgrade is completed.
Depends on #28.
> (PUP-4606) Test agent after upgrade

- README.markdown
> DOC-4765: added Windows Known Issues to ##Limitations in README

- manifests/osfamily/suse.pp
- spec/classes/puppet_agent_osfamily_suse_spec.rb
The last of the SLES 11 package issues have been fixed, making it ready
for inclusion in the module.
> (PE-10132) Add SLES 11 support

- manifests/params.pp
- Wrap _source usage to only assign if not windows
> (maint) Fix issue where we are breaking uri path for windows

- README.markdown
Added to #Limitations > ##Known Issues. Also added a brief note to the `arch` parameter description.
> FM-2915: added known issue for Windows

- manifests/params.pp
- manifests/prepare/package.pp
- spec/classes/puppet_agent_osfamily_aix_spec.rb
- spec/classes/puppet_agent_osfamily_darwin_spec.rb
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
I was having trouble pushing the specs commit to your branch @highb for #82 (permissions issue).
So I opened a new branch, and will merge this one.
> (PE-10956) Manage /opt/puppetlabs

- CHANGELOG.md
- README.markdown
- metadata.json
Assumes https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/101 will be merged.
> (packaging) Prepare for puppetlabs-puppet_agent 1.2.0

- README.markdown
@highb formatting ok? any others we should add?
> (maint) Add maintainers

- Gemfile
- Rakefile
- manifests/install.pp
- manifests/osfamily/suse.pp
Excludes a lint check we can't satisfy, and fixes up line length to
match 140 character limit.
> (maint) Fix up tests

- README.markdown
The commit updates the README with examples for Windows based properties.  This
commit also cleans up whitespacing for topic titles.
> (doc) Update documentation for Windows

- CHANGELOG.md
- metadata.json
Prepare the module for a 1.3.0 release
> (FM-5317) Prep for 1.3.0 release

- CHANGELOG.md
- README.markdown
Removed some double spaces, updated some style things and such.
> (FM-5320) Docs edits

- manifests/osfamily/debian.pp
- spec/classes/puppet_agent_osfamily_debian_spec.rb
This resource is Notified, so change it to a resource type that is refreshable. Set refreshonly to true.
> (Issue #132) Change Notify resource to Exec

- CHANGELOG.md
- metadata.json
> (MODULES-5235) Prepare 1.4.1 release

- metadata.json
inifile 2.0.0 is on its way so this modules dependency needs to be updated to use the new version
> (maint) bump inifile dependency

- .travis.yml
The previous issues of testing on Precise in Travis have been resolved.  This
commit changes to the more updated Trusty distribution and removes the issues
with the Future Parser testing on Precise.
> (maint) Test on Trusty for Travis

- .sync.yml
- CHANGELOG.md
- Gemfile
- manifests/init.pp
- manifests/install.pp
- manifests/osfamily/redhat.pp
- manifests/prepare/package.pp
- metadata.json
- spec/classes/puppet_agent_osfamily_aix_spec.rb
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_spec.rb
(maint) Mergeback 1.x into master
> (maint) Mergeback 1.x into master

- Gemfile
- task_spec/spec/acceptance/init_spec.rb
- task_spec/spec/spec_helper_acceptance.rb
This depends on the follow PRs
https://github.com/puppetlabs/bolt/pull/549
https://github.com/puppetlabs/beaker-task_helper/pull/30
> (BOLT-229) update to use new test helpers in BoltSpec and task_helpers

- tasks/version.json
> description of the task said puppet 5

- acceptance/Gemfile
To support https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/376
> (maint) Update minimum acceptance beaker-puppet version

- manifests/osfamily/suse.pp
This PR adds the functionality to refresh the local cache of the Suse package repository if the desired version of the Puppet Agent is not found.
> (MODULES-8432) refresh PA repo if the version is not in the local cache

- CHANGELOG.md
- metadata.json
> (maint) Release prep for 2.2.1

- Gemfile
Pin puppet-lint gem so that it will not have issue https://github.com/rodjek/puppet-lint/issues/891
> (maint) Pin puppet-lint to 2.3.6

- tasks/install_shell.sh
Reverts puppetlabs/puppetlabs-puppet_agent#457
Will not get in the next release and it will be redone
> Revert "(MODULES-10308) Allow downgrades when using apt"

- CHANGELOG.md
- metadata.json
> (maint) Prepare 3.0.0 release

- manifests/osfamily/windows.pp
- spec/classes/puppet_agent_osfamily_windows_spec.rb
Window FIPS x64 packages are stored under
windowsfips-x86_64
> (MODULES-10606) fix windowsfips upgrades

- tasks/install_shell.sh
Support for Linux Mint 20, LDME 4 in install script
> Support for Linux Mint 20, LDME 4

- CHANGELOG.md
- metadata.json
Prepare to release puppet_agent 4.1.0
> (maint) Release prep for 4.1.0

- metadata.json
Retrying to release after adding pdk as a dependency to please the
puppetlabs_spec_helper gods.
> (maint) Bump version to 4.1.1

- manifests/params.pp
- spec/classes/puppet_agent_params_spec.rb
Change default puppet collection to puppet7 on PE 2021.0 and newer
> (MODULES-10910) Default to puppet 7 for PE 2021.0

- CODE_OF_CONDUCT.md
> (maint) Add code of conduct

- .rubocop.yml
- files/rb_task_helper.rb
- tasks/facts_diff.json
- tasks/facts_diff.rb
- tasks/run.json
- tasks/run.rb
This adds a new task `puppet_agent::facts_diff` that
can be used to display facts differences between
Facter 3 and Facter 4 using `puppet facts diff` action.
> (MODULES-10925) Added facts_diff task

- CODEOWNERS
This work is for [PA-4133](https://tickets.puppetlabs.com/browse/PA-4133)
> (maint) Add phoenix to CODEOWNERS

- README.md
Add 'install_options' for gMSAs with link to Microsoft gMSA page. See DOC-5213 for details/background.
> DOC-5213 install_options for gMSAs

- task_spec/spec/acceptance/init_spec.rb
- tasks/install_shell.sh
Also added support for future platform additions that only have nightly builds available
> (FM-8943) Add Ubuntu 22.04 to puppet_agent module

- tasks/install_powershell.ps1
Most modern sites either require or are starting to require TLS 1.2. On older Windows systems the default security protocols for PowerShell 5 are SSL3 and TLS 1.0.
If using System.Net.WebClient, Invoke-WebRequest or Invoke-RestMethod to communicate with a site that has a higher TLS requirement requests will fail with the following error message:
`Could not create SSL/TLS secure channel.`
This PR adds a new function called `Set-Tls12` that will add TLS 1.2 to the list of active security protocols for the current session.
The above will only happen if the `Tls12` enum is not present in the current list.
This was causing failures on our nightly test runs for Windows Server 2016.
> (MODULES-11334) Handle TLS 1.2 on older Windows systems

- tasks/install_shell.sh
The typo was pointed out in PR review, but I only fixed one of the two places.
> Fix 2003 typo

- spec/classes/puppet_agent_osfamily_redhat_spec.rb
update spec to consider Rocky9 with el9.
> (PA-6502) Update puppet acceptance tests for Rocky9 intel

- task_spec/spec/acceptance/init_spec.rb
Added osx-15-x86_64 support in task acceptance tests
> (PA-6786): Added osx-15-x86_64 support in task acceptance tests
