- .travis.yml
- manifests/init.pp
- spec/classes/agent_upgrade_spec.rb
Extend spec testing to cover error case when using Puppet prior to 3.8,
and make no changes for Puppet 4.0+.
> (PUP-4559) Extend spec test to Puppet 3.7 and 4.0

- .gitignore
- spec/acceptance/class_spec.rb
- spec/acceptance/nodesets/centos-511-x64.yml
- spec/acceptance/nodesets/centos-66-x64.yml
- spec/acceptance/nodesets/centos-7-x64.yml
- spec/acceptance/nodesets/debian-609-x64.yml
- spec/acceptance/nodesets/debian-76-x64.yml
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/fedora-20-x64.yml
- spec/acceptance/nodesets/ubuntu-1204-x64.yml
- spec/acceptance/nodesets/ubuntu-1404-x64.yml
- spec/acceptance/server.cfg
- spec/spec_helper_acceptance.rb
Update acceptance tests and nodesets to run basic testing.
Added running multiple test scenarios. Tests can be run with SHA=b94d3b4f2db8de95f151b98a2c6054daddbb0d4d bundle exec rspec spec/acceptance, which downloads a vagrant VM (uses default.yml) and runs it. Specifying a SHA should allow tests to be run in Jenkins as well.
> (PUP-4567) Update acceptance infrastructure

- .travis.yml
- Rakefile
Add the future parser requirement to the Rakefile, so it doesn't have to
be specified on every specs run. This simplifies maintenance of the
Jenkins pipeline used to run specs.
> (PUP-4567) Add future parser in Rakefile

- Gemfile
- spec/acceptance/class_spec.rb
- spec/acceptance/nodesets/default.yml
- spec/spec_helper_acceptance.rb
Without this change, acceptance fails because `step` expects to be in
the context of a test. They also fail specifically in CI because the
master also includes the agent role.
* Pin to a working version of Beaker; BKR-283 tracks fixing it.
* Use default instead of agents for the machine being tested.
* Also only sync modules when needed.
> (PUP-4567) Fixes for acceptance and Beaker 2.12

- manifests/prepare.pp
- spec/classes/agent_upgrade_prepare_spec.rb
- spec/spec_helper_acceptance.rb
Prior behavior would move ssl files to the new default location in
Puppet-Agent, but wouldn't clear the ssldir setting. If ssldir was
previously set using a variable that's changed - such as vardir -
Puppet-Agent would look for SSL files in the wrong place.
Rather than trying to resolve where ssldir would point under
Puppet-Agent before installing Puppet-Agent, clear ssldir so we use the
default.
> (maint) Clear ssldir and use default

- manifests/init.pp
- spec/classes/agent_upgrade_spec.rb
In Puppet 4+, this module will continue to manage files related to the
upgrade. The main impact of this is reseting Puppet and Marionette
Collective configuration to defaults, which would be undesirable if
other changes are made.
Add a warning when running under Puppet 4+, reminding admins to remove
the module.
> (maint) Warn when using module in Puppet 4+

- .travis.yml
- Gemfile
Puppet 3.8 gems were released as Puppet 3.8.1. Use those for testing,
rather than git.
> (maint) Use Puppet 3.8 gems

- metadata.json
puppetlabs-stdlib 4.6.0 had future parser fixes in it, so require the
latest. This module requires future parser.
> (maint) Bump stdlib dependency for future parser

- manifests/prepare.pp
- spec/classes/puppet_agent_prepare_spec.rb
When the agent_upgrade module updates the mcollective's libdir, it
should prepend the new location rather than append it so that modules in
the new location are preferred.
> (PUP-4658) Prefer new mco libdir

- spec/acceptance/class_spec.rb
A prior commit for this ticket changed the order if mcollective's libdir
config, but not the acceptance test verifying it. Update the acceptance
test to pass again.
> (PUP-4658) Update acceptance for fix

- Gemfile
- spec/acceptance/class_spec.rb
- spec/classes/puppet_agent_prepare_spec.rb
- spec/spec_helper_acceptance.rb
- (maint) Update Beaker to latest and pin gems
- (maint) Remove work-around for BKR-262
- (PUP-4603) Use Puppet Server 2.1+
> (PUP-4603) Use Puppet Server 2.1+ for acceptance tests

- lib/facter/settings.rb
- manifests/prepare.pp
- spec/classes/puppet_agent_prepare_spec.rb
- spec/classes/puppet_agent_spec.rb
- spec/unit/facter/settings_spec.rb
Previously the ssldir was migrated monolithically. Unfortunately,
Puppet allows setting paths for several parts of the ssldir
individually. This now will take those disparate settings and combine
them into one ssldir post-migration.
It's a lot like voltron, but with more SSL.
This does not yet have acceptance, as beaker-rspec with vagrant and virtualbox is causing me grief. I'll get acceptance up ASAP, but for now the code itself is reviewable.
> (PUP-4690) Migrate SSL stuff based on individual settings

- lib/facter/mco_config.rb
- spec/acceptance/class_spec.rb
- spec/acceptance/files/client.cfg.erb
- spec/acceptance/files/server.cfg.erb
* (PUP-4746) Update mco settings custom fact
Without this change, mco_*_settings will only return the 1st declaration
of a setting in the config file. Update the fact to return values from
all declarations.
* (PUP-4735) Modify acceptance test for mco config
MCollective config files can contain multiple declarations of the same
property. Ensure acceptance testing covers that case.
> (PUP-4746, PUP-4735) Fix mco setting fact and add tests

- manifests/osfamily/debian.pp
- spec/acceptance/class_spec.rb
The module requires that apt update before installing the package.
Class level dependencies don't seem to enforce that, so add an explicit
sentinel to force the apt_update exec to run before finishing the repo
setup.
In some cases having the `puppet` service running when trying to run
`puppet agent` manually to verify idempotency results in an error, because
the service has also started an agent run at the same time.
`puppet apply` tests that the service is started after upgrade. Disable
starting the `puppet` service during agent runs to avoid the race
condition.
> (PUP-4478) Fix tests on Ubuntu

- lib/puppet/parser/functions/uri_host_from_string.rb
- manifests/init.pp
- manifests/osfamily/debian.pp
- manifests/osfamily/redhat.pp
- manifests/osfamily/suse.pp
- manifests/params.pp
- metadata.json
- spec/classes/puppet_agent_osfamily_debian_spec.rb
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
- spec/classes/puppet_agent_prepare_spec.rb
- spec/classes/puppet_agent_spec.rb
- spec/spec_helper.rb
This PR adds support for upgrading PE agents from 3.8 to 4.0.
Changes include:
* Passing the `source` parameter through to RedHat and Debian platforms
* Using the PE Masters repositories instead of FOSS for Debian and RedHat
TODO:
Update Windows source
Add support for following platforms:
SLES 10-11 (Zypper)
OSX
> (PE-10132) Add PE support for SLES 12, Debian, RedHat platforms

- .travis.yml
- Gemfile
- spec/spec_helper_acceptance.rb
BKR-314 and BKR-317 identified issues with using Beaker helpers for
upgrade scenarios. Simplify the acceptance setup by using Beaker helpers
now that they're fixed.
Beaker 2.15 was released with fixes for [BKR-314](https://tickets.puppetlabs.com/browse/BKR-314) and [BKR-317](https://tickets.puppetlabs.com/browse/BKR-317).
> (maint) Use BKR-314 and BKR-317 fixes

- Rakefile
- manifests/init.pp
- manifests/osfamily/debian.pp
- manifests/osfamily/redhat.pp
- manifests/params.pp
- manifests/prepare/mco_client_config.pp
- manifests/prepare/mco_server_config.pp
- manifests/prepare/puppet_config.pp
- manifests/prepare/ssl.pp
- manifests/windows/install.pp
- metadata.json
- Add Puppet version requirement to metadata
- Use Forge 'Puppet Approved' Lint settings
> (maint) Fixes for Forge score

- manifests/osfamily/debian.pp
- manifests/osfamily/redhat.pp
- spec/classes/puppet_agent_osfamily_debian_spec.rb
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
Previous to this commit, for PE users upgrading that had originally
installed via the simplified installer, the old repo definition was left
around pointing to a file path on the master that no longer exists due
to file path changes.
> (PE-10132) Remove old PE 3.8 repo

- README.markdown
- metadata.json
Ubuntu 14.10 never saw a Puppet 3.x package release, so this module has
no useful functionality on that platform. Remove the mention about
supporting it.
> (PUP-4808) Remove Ubuntu 14.10 support

- manifests/prepare/puppet_config.pp
- spec/classes/puppet_agent_prepare_spec.rb
Without this change, settings at the global level in puppet.conf
(outside a section) would not be cleared, and get inheritted by each
section. This would lead to incorrect configurations.
Also clear settings at the global level.
> (PUP-4886) Clear settings at global level

- CHANGELOG.md
> (maint) Provide changelog for 0.2.0 release

- README.markdown
Removes an accidental word, and notes that the module also makes changes
to client.cfg.
[skip ci]
> (doc) Fix minor typo and note changing client.cfg

- manifests/prepare/puppet_config.pp
- manifests/windows/install.pp
- spec/classes/puppet_agent_prepare_spec.rb
- spec/classes/puppet_agent_windows_install_spec.rb
This PR contains two fixes for PE users:
The first is reseting the `classfile` puppet.conf setting for mco inventory. The second is specifying the agent version to that of the compiling master instead of latest.
> Remove classfile puppet.conf setting, update for PE windows

- README.markdown
- manifests/config.pp
- manifests/init.pp
- spec/classes/puppet_agent_spec.rb
Briefly describes upgrade process, and points to Puppet docs for more
details. Also added more detailed description of the settings that are
changed during upgrade.
Removed an empty, unused class to clean up documentation.
> (maint) Clarify upgrade process in docs

- README.markdown
Windows Server 2003 and 2003R2 are unable to download resources from
pm.puppetlabs.com. Label this a known issue with a work-around, with
plans to address in a future release.
> (PUP-4925) Label a known issue with Server 2003

- manifests/init.pp
- manifests/install.pp
- manifests/install/remove_packages.pp
- manifests/osfamily/debian.pp
- manifests/osfamily/redhat.pp
- manifests/osfamily/suse.pp
- manifests/osfamily/windows.pp
- manifests/params.pp
- manifests/prepare.pp
- manifests/prepare/package.pp
- manifests/windows/install.pp
- metadata.json
- spec/classes/puppet_agent_osfamily_debian_spec.rb
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
- spec/classes/puppet_agent_spec.rb
- spec/classes/puppet_agent_windows_install_spec.rb
Introduces support for upgrading SLES 10 agents in PE. SLES 10 does not
have tools for securely handling remote package management.
* puppet-agent package is downloaded from a pe_packages fileserver mount
prepared separately on the master (in puppet_enterprise module)
* the package is downloaded with a File resource, but only if agent node
is not already at the current aio version
* because of limitations in the rpm package provider, it is not feasible
to get the install of the new puppet-agent package to run with '-U
--replacepkgs' flags that would allow rpm to correctly uninstall
conflicting superseded pe-* packages, so we remove those prior to
install. (Passing '-U --replacepkgs' in install_options parameter ends
up failing:
Error: Execution of '/bin/rpm -i "-U --replacepkgs" …
> (PE-10915) Add SLES 10 upgrade for PE

- manifests/init.pp
- manifests/install.pp
- manifests/install/remove_packages.pp
- manifests/osfamily/solaris.pp
- manifests/params.pp
- manifests/service.pp
- manifests/service/solaris.pp
- metadata.json
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_spec.rb
Based on #63.  This should not be merged until that PR is.
> (PE-12001) Add solaris 10

- manifests/init.pp
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
Prior to this commit the puppet_agent module did not accept
the sparc (sun4u/v) arch on Solaris 10.
This commit adds that arch to the accepted architectures, as well
as add special handling on Solaris 10 to use the "sparc" packages
on those arches.
> (PE-12001) Add Solaris 10 sparc to supported arch

- spec/classes/puppet_agent_windows_install_spec.rb
Before this commit when rspec-puppet would attempt to use the
'that_comes_before' matcher on a POSIX system with the file resource
when the file resource contained a windows path the test would fail.
This is because when puppet converts the catalog to the RAL catalog type
it pokes around in the actual types themselves. Since this is done on a
POSIX based system puppet attempts to validate the absolute path in the
file resource as a POSIX file path and fails since it is not a valid
absolute path.
This commit replaces the call to create the relationship graph to
determine where the windows file resource is at with a more basic test
to assert that the 'before' parameter is filled out on the resource
instead.
> (PE-13608) Do not convert windows file resource to RAL catalog

- manifests/init.pp
- manifests/install.pp
- manifests/install/remove_packages.pp
- manifests/osfamily/aix.pp
- manifests/params.pp
- spec/classes/puppet_agent_osfamily_aix_spec.rb
This change adds puppet agent support for AIX.
Support is gated by the 'aix' operatingsystem fact
and an architecture fact matching 'PowerPC_POWER[5,6,7]'.
This change uses the same strategy as osx for removing
unused packages as aix doesn't have fully fledged package
management for rpms.
> (PE-12002) Add AIX support

- lib/facter/settings.rb
- manifests/init.pp
- manifests/install.pp
- manifests/osfamily/windows.pp
- manifests/params.pp
- manifests/prepare/package.pp
- manifests/service.pp
- manifests/windows/install.pp
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
- spec/classes/puppet_agent_windows_install_spec.rb
- templates/install_puppet.bat.erb
Adds a PE-hosted MSI option for upgrading pre-2015 agents.
> (PE-10956) windows upgrade

- manifests/params.pp
- manifests/prepare/package.pp
Prior to this commit we removed management of `/opt/puppetlabs`.
This resulted in platforms that need to create
`/opt/puppetlabs/packages` before installation failing to work
because the parent directory was not present (because packaging
didn't create it yet)
This commit adds `/opt/puppetlabs` to the managed directories.
> (PE-10956) Manage /opt/puppetlabs

- manifests/osfamily/suse.pp
- spec/classes/puppet_agent_osfamily_suse_spec.rb
Previously, the exec to import the Puppetlabs GPG key made a call out to the
gpg binary to gather the hex value of the Puppetlabs GPG key. This call works
from the console with an ENV, but it doesn't work when automated because it
cannot find the relative homedir (~/.gnupg). To work around this, explicitly
set the value for root's .gnupg homedir in the unless command and expose it as
a variable should we need to deal with it later.
> (MODULES-3015) Fix SLES11 GPG key import issue

- manifests/init.pp
- manifests/install.pp
Puppet introduced the ability to use strings as the right operand of the regex
match operator, however, when testing this on 3.8.4 SLES11 boxes, I discovered
that they arose errors if the right operand wasn't a regular expression. This
commit corrects that to account for the errors.
> Use slashes for regex

- manifests/install.pp
Prior to this commit we didn't verify that the local MSI package
resource existed before trying to install with it.
This commit updates the windows install manifest to check that
the MSI package resource does exist before trying to install it.
> (PE-10956) Ensure local package resource defined on Windows

- CHANGELOG.md
- README.markdown
- metadata.json
This is a changelog and metadata update for the new 1.1.0 release of this module.
> Release Prep for 1.1.0

- manifests/osfamily/debian.pp
- spec/classes/puppet_agent_osfamily_debian_spec.rb
This fixes a typo in the apt settings when configuring the repo on the
MoM for PE. Without this, apt ignores the syntactically invalid
configuration option and attempts to use proxy configuration, which is
incorrect and so it fails.
> (maint) Fix typo breaking Debian upgrade for PE

- CONTRIBUTING.md
- spec/acceptance/nodesets/centos-5-x64.yml
- spec/acceptance/nodesets/centos-6-x64.yml
- spec/acceptance/nodesets/debian-6-x64.yml
- spec/acceptance/nodesets/debian-7-x64.yml
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/ubuntu-1204-x64.yml
- spec/acceptance/nodesets/ubuntu-1404-x64.yml
- spec/spec_helper_acceptance.rb
Changes to puppetserver defaults and beaker VM naming caused acceptance
to start failing when using Vagrant. Add the full VM name to
dns_alt_names and increase memory allocated to the master.
Previously acceptance tests would install puppet-agent 1.2.1, then
install the latest puppetserver prompting an upgrade to a new version of
puppet-agent. Now always install the latest puppet-agent and
puppetserver.
Also provide an environment variable, `PUPPET_CLIENT_VERSION` to allow
specifying the starting Puppet version for acceptance tests. This
provides a flexible way to run tests of Puppet from any prior version to
the latest.
> (maint) Fix acceptance using Vagrant configs, allow flexible starting Puppet version

- manifests/osfamily/redhat.pp
Amazon Linux looks enough like CentOS 6 that we can treat it that way for purposes of upgrading the puppet agent RPM. The end result of the change is that on Amazon Linux releases, the module configures the yum "pc1_repo" baseurl to the "el-6-${::architecture}" subdirectory instead of something
like "el-2015-x86_64" or "el-2014-x86_64".
This was tested on Amazon Linux 2015.03 and 2014.09.
> add support for Amazon Linux to puppet_agent::osfamily::redhat

- manifests/init.pp
- spec/classes/puppet_agent_spec.rb
Prior to this commit there was a lower bound on what versions of
puppet could be upgraded by the agent module. This has caused
users to rely on supplemental tools in some cases to facilitate
upgrades. In order to encourage upgrades and make the process
easier, we're removing the lower bound.
> (PE-13179) remove lower version requirement in code

- README.markdown
- manifests/init.pp
- manifests/osfamily/redhat.pp
- manifests/params.pp
- metadata.json
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
Updates supported platforms for new package releases, AIX PowerPC 8
hardware, and platforms that were added but not noted as supported.
Note that specific upgrade scenarios will still depend on Puppet being
installed from packages prior to upgrade. `puppet-agent` packages should
exist for all supported platforms.
> (maint) Update supported platforms

- .fixtures.yml
- manifests/init.pp
- manifests/install.pp
- manifests/install/remove_packages.pp
- manifests/install/remove_packages_osx.pp
- manifests/osfamily/debian.pp
- manifests/osfamily/redhat.pp
- manifests/osfamily/solaris.pp
- manifests/osfamily/suse.pp
- manifests/prepare.pp
- metadata.json
- spec/classes/puppet_agent_osfamily_aix_spec.rb
- spec/classes/puppet_agent_osfamily_darwin_spec.rb
- spec/classes/puppet_agent_osfamily_debian_spec.rb
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
- spec/classes/puppet_agent_prepare_spec.rb
- spec/classes/puppet_agent_spec.rb
- spec/classes/puppet_agent_windows_install_spec.rb
Prior to this commit we only allowed upgrades with this
module if the current puppet version was pre-4.
This commit removes that restriction and hopefully handles
all the edge cases involved in upgrade between new versions
and doesn't break FOSS. This feature should be tested
thoroughly.
> (PE-11531) Allow upgrades from Puppet 4+

- manifests/install.pp
- spec/classes/puppet_agent_spec.rb
Prior to this commit I assumed that I could ensure the package
version on Debian based platforms using the regular X.Y.Z version.
This commit fixes what is ensured on Debian platforms to
`X.Y.Z-1codename`, which is what apt expects.
> (PE-11531) Fix Debian ensure => version

- manifests/init.pp
- manifests/prepare.pp
- spec/classes/puppet_agent_prepare_spec.rb
- spec/spec_helper_acceptance.rb
The prior commit to enable puppet-agent to puppet-agent upgrades set an
expectation that a target version would always be required, either from
the master or explicitly specified as a parameter. That broke the
previous open-source upgrade behavior when upgrading from Puppet 3.x.
Restore that behavior by allowing the target version to be unspecified
if not on Puppet Enterprise and upgrading from Puppet 3.x. Also add the
new dependency puppetlabs-transition for acceptance testing.
> (maint) Re-enable open-source upgrades from 3.x

- manifests/prepare/package.pp
- spec/classes/puppet_agent_osfamily_windows_spec.rb
- spec/classes/puppet_agent_windows_install_spec.rb
When installing packages in a PE environment via pe_repo, only 64-bit
packages were supported on Windows. Update to also support 32-bit
packages.
> (PE-14463) Support 32-bit Windows via pe_repo

- Gemfile
- files/solaris_start_puppet.sh
- manifests/init.pp
- manifests/install.pp
- manifests/install/remove_packages.pp
- manifests/osfamily/solaris.pp
- manifests/params.pp
- manifests/prepare.pp
- manifests/service.pp
- manifests/service/solaris.pp
- metadata.json
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_spec.rb
- templates/solaris_start_puppet.sh.erb
This commit plumbs the puppet agent module to add Solaris 11 support.
This commit should be fairly consistent with how pe_repo handles
upgrading agents on Solaris 11 by updating the repo in
`/etc/puppetlabs/installer/solaris.repo` with the new puppet-agent
package and installing puppet-agent from there
Lots of things in this commit are less than ideal but the current state
of how Solaris 11 packaging handles files through
uninstallation/installation.
Since Solaris 11 will not uninstall packages if dependant packages are
also installed so the packages must be removed in a specific order or
else the puppet run will fail.
When uninstalling the pe-* packages, Solaris 11 decides to completely
remove everything in `/etc/puppetlabs/` which is why this commit has to
go through and copy it to a …
> (PE-12299) Add Solaris 11 support

- manifests/prepare.pp
- manifests/prepare/package.pp
Fixes a dependency cycle introduced by Solaris 11 work. Solaris 11
requires managing config files before preparing packages, because part
of preparing the package is saving /etc/puppetlabs where the configs are
stored.
On Windows, a dependency was introduced because the package is stored to
`C:/ProgramData/Puppet Labs/...`, and config files are also stored
there. So creating an order of configs before package prepare caused a
requirement that C:/ProgramData/Puppet Labs exists both before and after
managing config files. Fix that dependency cycle by mananging
`C:/ProgramData/Puppet Labs` earlier.
> (maint) Fix a dependency cycle introduced on Windows by Sol11 work

- manifests/params.pp
- spec/classes/puppet_agent_spec.rb
Compilation should not require `pe_compiling_server_aio_build`. Skip
calling it if not defined even if `is_pe` is true.
> (maint) Fix issue #98, don't require `pe_compiling_server_aio_build`

- spec/classes/puppet_agent_spec.rb
Typo in previous spec meant it only skipped SLES (as a PE-only
platform). It must also skip Solaris.
> (maint) Fix spec that should've skipped Solaris

- manifests/install.pp
- manifests/install/remove_packages.pp
- manifests/install/remove_packages_osx.pp
Prior to this commit we were removing the puppet-agent package
if the `package_version` happened to be unset, due to the
behavior of `versioncmp`. This is obviously not what we want to
have happen.
This commit updates all of the calls that compare `package_version`
with `aio_agent_version` with `versioncmp` to be gated on
`package_version` not being undef, thus preventing the packages
from being removed on every run.
> (PE-11531) Don't remove packages if package_version undef

- manifests/init.pp
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
Version numbers for development packages on Solaris 11 need to be
munged, which happened for the file name. However Solaris 11
puppet-agent upgrades use the version number, which was not correctly
munged. Fix that, and add testing for development version numbers.
> (maint) Fix handling dev versions on Solaris 11

- manifests/init.pp
- manifests/install.pp
- manifests/install/remove_packages.pp
- manifests/install/remove_packages_osx.pp
- spec/classes/puppet_agent_osfamily_darwin_spec.rb
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
- spec/classes/puppet_agent_windows_install_spec.rb
Prior to this commit we had the same AIO upgrade expression scattered
in 3 different places with slightly different syntax. Also, we did not
account for the fact that `aio_agent_version` is a PE only fact.
This commit creates a `$aio_upgrade_required` var in the main class
that will 1) always be true if not PE and `package_version` is set 2) be
true if `aio_agent_version` and `package_version` are set and
the `aio_agent_version` is less than (-1) the `package_version`.
> (PE-11531) Centralize check for aio upgrade

- manifests/install/remove_packages_osx.pp
- spec/classes/puppet_agent_osfamily_darwin_spec.rb
Turns out we don't need to bother forgetting the old package when doing
an OSX upgrade between AIO versions, that was only necessary for 3.8
upgrades.
> (PE-11531) Stop OSX from forgetting packages

- lib/facter/settings.rb
- manifests/windows/install.pp
- spec/classes/puppet_agent_windows_install_spec.rb
Prior to this commit there was an issue where the inherit permission
value on the `client_datadir` folder was being lost, causing the folder
to be inaccessible to the MCO/PCP daemons.
This commit ensures that directory has the proper inherit permission,
if it appears that it does not have it. For more details: PE-15036
> (PE-15036) Fix Windows permission inheritance

- manifests/init.pp
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_windows_install_spec.rb
Prior to this commit the module would always upgrade with dev
builds because they have a git SHA appended to the end, which
`versioncmp` considers to be greater than the version reported
by `aio_agent_version`, which lacks the extra git sha characters.
This commit updates the update check to strip the git sha when
comparing the `aio_agent_version` to the requested `packace_version`.
> (PE-11531) Fix upgrade issue with dev builds

- manifests/install.pp
- manifests/prepare/package.pp
- spec/classes/puppet_agent_osfamily_windows_spec.rb
Prior to this commit the path being used to locate the local
prepared copy of the windows MSI had a bug where one area of
the module would use a forward slash, and the other would use a
backslash. Additionally, the install class did not depend on the
prepare step's file resource that is created and instead used the
`defined` function to check for the file.
This commit updates the slashes to be consistent and adds an
explicit require on the File resource that prepares the local
copy of the MSI.
> (MODULES-3304/PE-15256) Fix Windows 2008 upgrades

- templates/install_puppet.bat.erb
- It can be difficult to determine when an agent upgrade has actually
completed on Windows, because a sequence of events must occur:
* the current puppet run must complete, preventing file locking
* the install_puppet.bat script waits 5 seconds, then infinite
loops until a given PID is no longer running (from prior run)
* the actual MSI must run to completion (it may encounter issues if
for some reason any Puppet services / processes are still running)
This can make it very difficult to implement a deterministic
behavior around waiting until an upgrade completes in an effort to
synchronize / orchestrate additional actions post-upgrade.  This
is of particular importance to tests that may eagerly perform
validations on the upgrade prior to the upgrade actually finishing.
- Improve the …
> (MODULES-3433) Write Windows PID file on upgrade

- metadata.json
- As part of the 1.2 release, the scope of upgrades was changed to include 3.7.  Makes sure that
metadata.json reflects this.
> (maint) Update metadata.json for Puppet 3.7

- spec/classes/puppet_agent_windows_install_spec.rb
- templates/install_puppet.bat.erb
- Previously, upgrades could fail as a result of the pxp-agent service
holding file locks.  While we have been previously aware of the
potential for this isssue, given pxp-agent runs under nssm.exe on
Windows, prior investigation had shown this to not be an issue on
silent installations (see PA-65).
However, in practice, while upgrading from puppet-agent 1.4.2 to
puppet-agent 1.5.0, a running pxp-agent service is preventing
installs from proceeding as requested with a 1603 failure. NSSM.exe
is not affiliated with the pxp-agent service in the MSI and therefore
the Restart Manager has no understanding that it will be later
shutdown and unlocked.
The solution is to simply request a `net stop pxp-agent` prior to
running the MSI.  It's very important that this be done *after* the
puppet run …
> (MODULES-3449) Stop Windows pxp-agent service

- manifests/osfamily/debian.pp
- spec/classes/puppet_agent_osfamily_debian_spec.rb
This commit disables client SSL verification on Xenial. We had to
do this in order to work around an issue where client ssl seems to
not be compatible with the SSL certs that PE uses. The root cause of
this change, and why it only occurs in Xenial, is unknown at this time.
> (PE-16317) Disable client SSL verification on Xenial

- templates/install_puppet.bat.erb
Per #126 the windows agent upgrade batch script does not preserve the agent configured environment. This change will persist the environment config post upgrade.
Additionally the updated gems for Lint cause 140 character check issues, and complains about puppet:// source paths where modules/ is not in the string. I have suppressed these lint checks as they cause issues with the existing untouched code base.
> Explicitly setting environment to nodes current environment

- manifests/prepare/ssl.pp
and give a helpful error message if it is.
stringify_facts = false is a stated requirement in the documentation.
However,  if that is missed, or if the occasional agent has it unset (and therefore true) then the error message is indecipherable. To aid the unlucky troubleshooter, this PR will identify the consequence of stringify_facts being true and a particular data structure being a String instead of a Hash.
> Test if stringify_facts = true on agent

- README.markdown
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- manifests/windows/install.pp
- templates/install_puppet.bat.erb
Allow setting the INSTALLDIR option for the Windows MSI.
> (MODULES-3571) Allow setting install_path for MSI

- templates/install_puppet.bat.erb
- The previous checks for PID running uses a combination of tasklist,
findstr and some more cryptic batch-isms to detect if a puppet
agent is currently executing (by PID).  This check also relies on
the English string "No tasks are running", because tasklist.exe
doesn't set exitcodes as desired when the query is not a match.
C:\Users\Administrator>tasklist.exe /FI "PID eq 1234" /NH
INFO: No tasks are running which match the specified criteria.
C:\Users\Administrator>echo %ERRORLEVEL%
0
There are a couple of alternative methods for achieving the
desired functionality.  The simplest is qprocess.exe:
C:\Users\Administrator>qprocess 1234
No Process exists for 1234
C:\Users\Administrator>echo %ERRORLEVEL%
1
C:\Users\Administrator>qprocess 32936
USERNAME              SESSIONNAME         ID …
> (MODULES-3636) Upgrade on non-English Windows

- templates/install_puppet.bat.erb
- Previously, the batch file would wait for an infinite amount of
time for the calling Puppet process to exit, before it would
proceed with an upgrade.
Prior to rewriting the PID check with wmic, this could cause an
infinite loop when trying to match an unlocalized string.
Since infinite loops are never a good idea, cap the wait limit to
120 seconds, and log an event log message under Puppet / ID 101
that the agent upgrade failed.
This should improve the end user experience under failing
circumstances.
> (MODULES-3434) Wait 120 seconds for Windows agent

- templates/install_puppet.bat.erb
Previously the script was using the timeout.exe application however this
attempts to redirect STDIN and during a headless operation, for example during
an actual puppet run, this throws an error and does not wait the proper time.
This commit changes the wait method to use ping.  Ping waits 1 second between
attempts therefore a simple `ping 127.0.0.1 -n 6` will pause for 5 seconds.
This commit also changes the location of the PID file slightly.  Previously it
used `%TEMP%` however this variable can be removed or be in an unexpected place.
Instead the PID file is always placed in the same directory as the
script (`%~dp0`).
To assist in debugging upgrade failures the install batch file also outputs
all environment variables prior to running.
This PR builds on #136 and #135
> (MODULES-3657) Fix waiting on Windows during upgrade

- Rakefile
- spec/spec_helper_acceptance.rb
**(maint) Add puppet-lint workarounds for CI**
Our CI setup puts extra files in the project workspace, which
puppet-lint then tries to lint. This fails for older versions of Puppet.
**(maint) Fix test to use valid certnames**
Fix up SSL configuration for use with fixes in stomp 1.4.1.
Without this the activemq-stomp connection will reject the connection.
> (maint) Add puppet-lint workarounds for CI, use valid certnames

- manifests/prepare/puppet_config.pp
puppet-lint added checking variable case on a bug fix release. Address
the noted issues.
> (maint) Fix linting

- manifests/prepare/package.pp
- manifests/prepare/puppet_config.pp
See issue:
https://github.com/puppetlabs/puppetlabs-puppet_agent/issues/146
All I did was set the Windows permissions on that file to be 0664 and leave everything else 0644.  I don't know if this is the correct way to patch what I was seeing or not, but I figured I'd put in the PR anyway.  I'll have more testing done in the next couple of days as I move all my agents to PE 2016.
> Set perms for Windows package differently than for Linux

- README.markdown
- manifests/init.pp
- manifests/osfamily/debian.pp
- manifests/osfamily/redhat.pp
- manifests/osfamily/solaris.pp
- manifests/osfamily/suse.pp
- spec/classes/puppet_agent_osfamily_debian_spec.rb
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
This is intended to enable users to utilize existing systems management
tools and internally hosted repositories to ensure agent upgrades
> (MODULES-3872) Updated to provide the ability to disable configuration of PE/FOSS repositories

- manifests/install.pp
- spec/classes/puppet_agent_spec.rb
This commit modifies the install logic when `osfamily` is `RedHat`
to accommodate for the `fedoraf` package suffix when the OS is
fedora rather than an `el` derivative.
Prior to this commit the `puppet-agent` package would be suffixed
with `el` which does not match the package naming convention for
fedora.
> (PE-17508) Fix puppet-agent suffix on fedora

- manifests/osfamily/redhat.pp
- manifests/osfamily/suse.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
the current code on Suse simply converts all letters to the character 'a' and causes each run to re-import keys - so just for consistency sake, setting redhat/suse to both use the [:upper:] [:lower:] syntax
* edit - I should clarify - this doesn't happen on all systems,  but the behavior appears to occur on older versions of coreutils
> updated unless condition on Suse/Redhat GPG key imports to ensure downcasing

- README.markdown
Note that log locations that have been explicitly configured are not
reset when upgrading from Puppet 3.
Closes #157.
> (docs) Note unchanged config options

- manifests/init.pp
- manifests/osfamily/redhat.pp
- manifests/params.pp
Puppet 4 warns about unknown variables, as in
```
Warning: Unknown variable: '::platform_tag'. at
/root/puppet/modules/puppet_agent/manifests/params.pp:75:17
Warning: Unknown variable: '_package_version'. at
/root/puppet/modules/puppet_agent/manifests/init.pp:108:8
```
Fix by avoiding unknown variables, or guarding variables we know aren't
defined. Fixes #156.
> (MODULES-3896) Avoid unknown variables

- manifests/init.pp
This commit updates the logic for cleaning a vanagon package version
name to be compatible with the IPS requirements for solaris ll p5p
package naming. It adds the same logic found in vanagon itself for
removing any leading zeros from the dotted segments of the version
string.
Prior to this commit, leading zeros in a version segment were left
in the package name which violates p5p naming rules. This caused
vanagon builds containing such a version to fail the install
process.
Ref:
[vanagon ips version code](https://github.com/puppetlabs/vanagon/blob/master/lib/vanagon/platform/solaris_11.rb#L94-L107)
[Solaris 11 package versioning](http://www.oracle.com/technetwork/articles/servers-storage-admin/ips-package-versioning-2232906.html)
> (PE-17663) update logic for solaris 11 package name

- manifests/init.pp
- manifests/install.pp
- spec/classes/puppet_agent_osfamily_aix_spec.rb
Prior to this commit, puppet-agent upgrades on AIX were constrained to
POWER 5-7 architectures.
However, if Puppet is already running on a supported version of AIX, it
should be safe to assume we're on a supported POWER version.
This commit removes the POWER version constraint, allowing upgrade on
POWER8 and higher architectures.
> (FM-4989) Remove POWER version constraint for AIX

- .fixtures.yml
Previously the test fixtures used pointed to the head of git repos however there
is no certainty that the code at HEAD is working.  This commit changes the
fixtures to use the forge which uses publicly released modules.
> (maint) Use the forge for test fixtures

- README.markdown
This commit corrects `rpos` to `repos`, the correct spelling, in
README.markdown.
Signed-off-by: Moses Mendoza <moses@puppet.com>
> (maint) correct spelling error in README.markdown

- spec/spec_helper_acceptance.rb
Prior to this commit, throughout acceptance tests whenever the
teardown_puppet_on(host) method of spec_helper_acceptance.rb was called,
several errors would result of the form:
Error: Cannot create /etc/puppetlabs/puppet; parent directory /etc/puppetlabs
does not exist
Error: /File[/etc/puppetlabs/puppet]/ensure: change from absent
to directory failed: Cannot create /etc/puppetlabs/puppet; parent directory
/etc/puppetlabs does not exist
Error: Cannot create /etc/puppetlabs/code;
parent directory /etc/puppetlabs does not exist
...
This is because during the puppet apply, puppet was attempting to apply the
Settings catalog, in which resources are created from puppet config settings
and puppet attempts to validate them[1]. Normally this is fine, but because
we've just purged puppet itself, …
> (MODULES-3953) avoid applying settings catalog in acceptance

- lib/facter/settings.rb
- manifests/params.pp
- manifests/prepare/ssl.pp
- spec/classes/puppet_agent_spec.rb
- spec/unit/facter/settings_spec.rb
Without this check, you get incomprehensible results. The is_pe fact is
evaluated as true, and so the class bails out. In some cases the
info() function isn't loud enough and so it appears to do nothing.
This just fails hard and makes it obvious why.
> (MODULES-3951) Add explicit check for stringify_facts

- .fixtures.yml
The 4.13 release of the puppetlabs-stdlib module deprecates many
functions, breaking all of the tests in the puppet_agent module. Until
we can update the tests to handle the deprecations, we need to stay on
4.12 for testing.
> (MODULES-3962) Pin stdlib module to 4.12

- spec/acceptance/class_spec.rb
This commit adds tests to the acceptance test suite in `class_spec.rb` for
confirming that the manage_repo parameter does, in fact, do what it says.
Specifically, we test that puppet created the repo by applying the
'puppet_agent' class with no params (implying default value of true for
`manage_repo`) and then specifically ensuring the repo present with puppet and
catching (failing) on any resultant changes. Then we remove the repo
configuration and apply the puppet agent class again but with `manage_repo =>
false`, and ensure that the repo configs are not re-created (again by catching
changes).
> (MODULES-3872) add acceptance test for manage_repo param

- MAINTAINERS
- README.markdown
This PR builds on https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/174. It adds Moses and Glenn as maintainers to puppetlabs-puppet_agent, in addition to the existing maintainers.
> (maint) Add Moses and Glenn as maintainers

- Gemfile
- Rakefile
This commit adds a rake task (copied from puppetlabs-apt) that uses
beaker-hostgenerator to generate a nodeset compatible with our vmpooler. This
enables local testing with the vmpooler, in addition to the default testing
using vagrant. Note that we still need to tell beaker to look for our nodeset
using BEAKER_setfile=<nodeset>. Credit to @DavidS for the original contribution
to puppetlabs-apt.
Signed-off-by: Moses Mendoza <moses@puppet.com>
> (maint) add task for generating nodesets for testing

- README.markdown
- spec/classes/puppet_agent_osfamily_aix_spec.rb
Starting with the 1.3.0 release of the puppet_agent module, use of the
module is no longer constrained by the PowerPC architecture version of
the target system's underlying hardware.
Here we update README.markdown to reflect this change.
> (MODULES-3912) Remove POWER8 hardware constraint from README

- manifests/init.pp
- spec/classes/puppet_agent_windows_install_spec.rb
Hey there,
At some point the url schema for Windows agents in the repo was updated to `https://downloads.puppetlabs.com/windows/puppet-agent-${version}-${arch}.msi`, but the module is still looking for agent packages at `https://downloads.puppetlabs.com/windows/puppet-agent-${arch}-${version}.msi`
This updates the filename to point to the correct url.
Please let me know if this needs anything else.
Thanks! ❤️
> (Modules-3970) Update puppet windows agent download url schema

- metadata.json
Since the last release, Ubuntu 16.04 and Fedora 23 packages have been
made available for puppet-agent. Update the metadata to reflect that
upgrades on those platforms should be supported.
> (maint) Update supported platforms based on available packages

- Gemfile
- manifests/prepare/package.pp
Prior to this commit we attempted to "save" the master from having to
perform checksum logic on the puppet-agent tarball by only attempting
to checksum if the master_agent_version != aio_agent version. Which
would be true if
A) The agent was pre-aio (< 3.8)
B) The agent needed to be upgraded
but not true if the agent was already up to date previous to the
puppet_agent module being installed. If it was already up to date,
this prepare step would not occur, and the module would later attempt
to install using a tarball that had not been copied over.
This commit removes the master_agent_version != aio_agent version
check and replaces it with just checking for `is_pe`, since we
depend on the `pe_build_version` function. It also specifies
the `sha256lite` checksum method should be used. This …
> (MODULES-4030) Always prepare package

- manifests/install.pp
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
Solaris 10 packaging, when combined with zones, is super weird. The
Puppet Enterprise frictionless install has historically made sure that
the agent is installed per-zone. However, the `puppet_agent` module
did not. This leads to conflicts when upgrading agents - once the
Global zone is updated, trying to upgrade the other zones will fail,
since the `puppet-agent` package is "already installed".
This changes solaris 10 packaging to be per-zone, which matches how we
have historically done that deployment.
> (MODULES-4092) Install solaris 10 package per-zone

- .travis.yml
- CONTRIBUTING.md
- Gemfile
- manifests/prepare/puppet_config.pp
- spec/classes/puppet_agent_spec.rb
Module config got out-of-sync with expectations in our Jenkins setup.
Fix it to use PUPPET_GEM_VERSION to select Puppet version for testing,
and change the default to a more recent version of Puppet.
> (maint) Fix config for Jenkins

- Gemfile
- manifests/prepare/package.pp
Puppet 3 does not handle custom file checksums correctly. We can only
use sha256lite on puppet 4.
> (maint) Only use sha256lite when we are already on AIO

- CHANGELOG.md
We discovered a bug at the last minute and couldn't ship on the
16th. Time to try again.
[skip-ci]
> (maint) Bump release data in CHANGELOG

- manifests/init.pp
- manifests/osfamily/redhat.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- We have system wide proxy for all repos and this is critical for us so we can use the module
> (MODULES-4236) Disable proxy for yum repo as it will not pass through to Puppet Server and will not hand over the certs.

- .gitignore
- README.markdown
- manifests/init.pp
- manifests/windows/install.pp
- spec/classes/puppet_agent_windows_install_spec.rb
- templates/install_puppet.bat.erb
During investigation into network stack restarts on Windows (https://tickets.puppetlabs.com/browse/PA-663),
it was found that a file lock on puppetres.dll was causing MSI to trigger an
unforseen service restart. This commit adds an installation option to the
puppet_agent module called `msi_move_locked_files` which premptively moves files
that can cause locks, prior to the upgrade, so that the upgrade can complete
without a service restart.
Acceptance tests will be moved to another ticket due to complexity.
> (MODULES-4207) Optionally move puppetres.dll on Windows upgrade

- spec/acceptance/class_spec.rb
- spec/spec_helper_acceptance.rb
Previously some runs would communicate with the default `puppet`
address. Set configuration so that all communication uses the test
server.
> (FM-5839) Ensure server is set for all actions

- manifests/init.pp
- manifests/prepare.pp
After fixing those 3 facts puppet module started to work with strict_variables set to true
> Use getvar for facts that doesn't exist in my environment

- lib/facter/puppet_agent_appdata.rb
- manifests/params.pp
- spec/classes/puppet_agent_osfamily_windows_spec.rb
- spec/classes/puppet_agent_windows_install_spec.rb
Module params depended on `::common_appdata` being defined, which exists
in PE but not necessarily other environments. Add a new custom fact - so
names don't conflict - to cover this case.
> (MODULES-4241) Add custom fact puppet_agent_appdata

- manifests/prepare.pp
- manifests/windows/install.pp
- spec/acceptance/class_spec.rb
- spec/acceptance/files/client.cfg.erb
- spec/acceptance/files/server.cfg.erb
- spec/acceptance/files/uninstall.ps1
- spec/spec_helper_acceptance.rb
- templates/install_puppet.bat.erb
Update test setup to work with Windows paths and install behavior.
Fixes #197. Depends on #200.
> (MODULES-4241) Enable Windows acceptance testing

- manifests/params.pp
Prevent failures when STRICT_VARIABLES='yes'.
> Ensure all variables are populated

- manifests/prepare/mco_server_config.pp
PE modules also manage server.cfg, so only manage it if not already done
so by other modules. Fixes #193.
> (maint) Only update server.cfg if not already managed

- MAINTAINERS
In reality I have not been able to contribute to this project and am fully
consumed maintaining Puppet. Remove me from the list of maintainers to reflect
reality.
Signed-off-by: Moses Mendoza <moses@puppet.com>
> (maint) remove Moses as a maintainer

- spec/spec_helper_acceptance.rb
The work for enabling Windows acceptance apparently missed a run of
Puppet after the uninstall. It's not clear how this was missed, but the
new logic here makes sense.
> (MODULES-4241) Fix Windows acceptance

- README.markdown
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- manifests/windows/install.pp
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_spec.rb
- spec/classes/puppet_agent_windows_install_spec.rb
- templates/install_puppet.bat.erb
Previously it was not possible to pass additional installation parameters during
an upgrade process.  In the case of MSI files this could be sensitive passwords
or other public MSI properties.  In the case of package resources, additional
options could not be added to the package resource.
This commit adds a parameter called `install_options` which mirrors the
`install_options` parameter from the package resource and then passes this down
so that it is invoked on installation (either by a package resource or in the
batch file to install the MSI)
> (MODULES-4214) Add additional installation parameters during upgrade

- manifests/init.pp
- manifests/params.pp
- spec/classes/puppet_agent_spec.rb
Previously a bug in the logic including the puppet_agent::service class
prevented it from being applied on non-PE installs using Puppet 4. Fix
it so that services are now managed for non-PE installs under Puppet 4.
> (MODULES-3994) Manage services on Puppet 4

- manifests/osfamily/redhat.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
Prevents re-running exec to install GPG keys on RedHat systems where the
`tr` failed.
Closes #214.
> (MODULES-4478) Fix `tr` invocation for some versions of RedHat

- manifests/osfamily/suse.pp
- spec/classes/puppet_agent_osfamily_suse_spec.rb
This commit updates the file location for the GPG keys used on
the SLES. The key files have moved from `RPM-GPG-KEY-puppetlabs`
to `GPG-KEY-puppetlabs` previously. This commit simply brings this
location current for the SLES platform so that the keys can be
properly found.
> (MODULES-4521) Update suse GPG file location

- .fixtures.yml
puppetlabs-stdlib 4.13.0 introduced deprecation warnings about using
`validate_re`. The suggested replacement - `validate_legacy` is only
supported in Puppet 4.4+. This makes it a challenge to write and test a
module that needs to work with Puppet 4+. For now pin puppetlabs-apt to
use 2.3, to avoid requiring a newer version of stdlib as required in
puppetlabs-apt 2.4+.
> (maint) Pin fixtures to puppetlabs-apt 2.3.0

- metadata.json
This increases the minimum version requirement for the
puppetlabs-transition module from 0.1.0 to 0.1.1.
There was a very important bug fix in 0.1.1 that allows puppet-agent
to be upgraded on AIX servers. Prior versions were unable to
automatically update puppet-agent due to inconsistent state caching.
See: https://github.com/puppetlabs/puppetlabs-transition/pull/8
> (MODULES-4732) Bump transition dependency to 0.1.1

- manifests/init.pp
- manifests/install.pp
- manifests/prepare/package.pp
- spec/classes/puppet_agent_osfamily_aix_spec.rb
We did not add new packages for AIX 7.2. Instead, we use the AIX
7.1 packages. This adds the necessary logic to point AIX 7.2 at
the older packages.
> (PA-1160) Add support for AIX 7.2

- manifests/params.pp
- spec/classes/puppet_agent_spec.rb
- spec/spec_helper_local.rb
Remove default value for Fact ::puppet_stringify_facts and allow Puppet version being tested to provide it (thus simulating it's non-existence in Puppet 4).
Fixing the logic around testing for $::puppet_stringify_facts in Puppet 4.
> puppet_stringify_facts fixes for Puppet 4

- spec/classes/coverage_spec.rb
All spec files need to include spec_helper, or parallel specs runs will
fail.
> (maint) Include spec_helper so parallel specs succeed

- CHANGELOG.md
- manifests/osfamily/redhat.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
RedHat 5 uses an old OpenSSL version that can't connect to
www.puppetlabs.com using HTTPS. Use HTTP - which is what the repos setup
by Puppet's repo packages use - instead. That should still be secure
since we use signed packages and the GPG keys are included with this
module.
> (maint) Use http for RedHat repos

- .travis.yml
- MAINTAINERS
- metadata.json
Travis CI switched from Precise to Trusty, but don't have Ruby 2.1
builds for Trusty. Pin to Precise so tests against Ruby 2.1 continue to
work.
> (maint) Fix Travis CI

- templates/solaris_install.sh.epp
This makes it easier to test when the upgrade is still in-progress, and
mirrors how the Windows upgrade is handled. It's either this or we grep
ps for running upgrades. Currently used in upgrade acceptance tests.
This pattern - laying down a file in /tmp/puppet_agent_upgrade.pid -
should be followed for any scripts used to perform async upgrades to
maintain testability with our current test suite.
> (maint) Add pid file to Solaris upgrade

- manifests/osfamily/redhat.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
We made a couple of changes to how Yum repo paths are constructed
in puppet 5:
1) We now put the repo name (puppet5) before the OS name/version
2) We no longer put an extra 'f' in fedora repos
This updates the module to only use the old repo path
construction if the collection is 'PC1'. Otherwise, we use
the newer construction (under the assumption that we won't change
again for puppet 6)
> (MODULES-5633) Add support for Puppet 5 on Redhat osfamily

- manifests/params.pp
- spec/classes/puppet_agent_spec.rb
* The code to check that stringify_facts was true,
assumed that the fact itself would be a boolean
* Ironically, if it’s true... the fact is a string!
* We can fix this by simply adding a str2bool
* Adds extra unit test to check both cases
> (MODULES-5944) Fixes failure for stringify_facts

- README.markdown
- manifests/prepare/stringify_facts.pp
- spec/classes/puppet_agent_prepare_stringify_facts_spec.rb
* `stringify_facts` is currently not configurable 
in the module
* Lets add a class to configure it
* AND add docs on using the `puppet_conf` task to
Do it
> (MODULES-5953) Adds ability to set stringify_facts

- manifests/osfamily/debian.pp
- spec/classes/puppet_agent_osfamily_debian_spec.rb
The private key is not world readable and apt now runs as an
unpriveledged user. This means apt can no longer read the private
key. We don't validate the client so we're removing the usage of the
private key to communicate with master.
> (PE-22810) Removed _client_cert_verification

- manifests/install.pp
- spec/classes/puppet_agent_osfamily_aix_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
When upgrading from a puppet-agent package, use rpm to do an inplace
upgrade rather than the previous method of uninstalling the old package
before installing the new one. This avoids an issue when upgrading
Puppet 5 installs where the upgrade run tries to use files that have
been uninstalled.
> (MODULES-5979) Use rpm upgrade for puppet-agent upgrades

- README.markdown
- manifests/windows/install.pp
- spec/classes/puppet_agent_windows_install_spec.rb
- templates/install_puppet.bat.erb
Set REINSTALLMODE for Puppet Agent Upgrade/Downgrade defaulting to
"amus" which forces all files to be replaced regardless of version or
checksum.
> (MODULES-5622) Add REINSTALLMODE for win install

- manifests/init.pp
- manifests/osfamily/debian.pp
- manifests/osfamily/redhat.pp
- manifests/osfamily/suse.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
Managing the /etc/pki directory inside the puppet_agent module can be problematic for organizations that manage gpg keys and settings in other modules.  Adding a manage_pki_dir parameter that defaults to true allows some flexibility to the end users.
> Make management of /etc/pki directory optional

- manifests/install.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
While the EL6 packages work for Amazon Linux (https://github.com/puppetlabs/puppetlabs-puppet_agent/blob/master/manifests/osfamily/redhat.pp#L15-L16), I get this error when ensuring a package version.
This PR fixes that.
```
Error: Could not update: Failed to update to version 5.1.0-1.el2017, got version 5.1.0-1.el6 instead
Error: /Stage[main]/Puppet_agent::Install/Package[puppet-agent]/ensure: change from '5.1.0-1.el6' to '5.1.0-1.el2017' failed: Could not update: Failed to update to version 5.1.0-1.el2017, got version 5.1.0-1.el6 instead
```
> fix dist tag on Amazon Linux (avoids issue when ensuring package version)

- Rakefile
While we support Puppet 3, we can't use puppetlabs-translate as it uses
Puppet 4 functions. Disable the i18n check in PuppetLint that requires
messages to be decorated with the translation function.
> (maint) Disable PuppetLint i18n check

- README.markdown
-   Use backticks for code blocks.
-   Add a deprecation notice to the `stringify_facts` setting.
-   Move a sentence about compilation back to the setup requirements.
-   Clarify some text around `install_options`.
> (MODULES-6095) Review docs for release.

- metadata.json
- spec/classes/puppet_agent_osfamily_debian_spec.rb
According to ticket 6280 (https://tickets.puppetlabs.com/browse/MODULES-6280):
This PR updates the maximal compatible version of puppetlabs/apt to 4.1.0.
Unit tests were successful (with updated .fixtures.yml)
> ensure compatibility to puppetlabs/apt > 3.0.0

- .sync.yml
- .travis.yml
Previously the module was tested in both Travis and private Jenkins CI systems
however this is no longer required.  This commit moves the spec tests that
are tested in Jenkins and moves them to Travis;
* Only test puppet agent and ruby combinations that are installed in AIO installs
* Split out validate and lint checking to only happen once per job not for all
matrix cells
* Now tests on Puppet latest 3.8, first 4.0, latest 4.7.x, 4.10.x and 5.x gems
* The Hiera Gem needs to be set on Puppet 4.7.1 as it has incompatibilites with
later hiera gem versions (4.4.2)
* Brings the Travis CI config file into a similar format as that used by the PDK
to make migration easier later.
* The Travis file needs to remain unmanaged until it supports setting the
bundler_args setting
> (MODULES-6688) Use travis for CI testing, instead of Jenkins

- templates/install_puppet.bat.erb
Previously it was possible to get into a strange race condition where the MSI
was able to propertly stop the MCollective and Puppet service prior to upgrade.  This
PR attempts to stop the mco and puppet services prior to the MSI being invoked, giving
the service more time to stop correctly.
This PR also adds some helpful information into the installation log for use during debugging failed installations.
>  (PE-23563) Stop MCO and Puppet prior to MSI install 

- manifests/osfamily/darwin.pp
- spec/classes/puppet_agent_osfamily_darwin_spec.rb
The previous regex used a character class instead of a union to
match the major Mac OSX product version, which would match values
such as "10.14", "10.15". This meant that the puppet_agent module
would think these are supported platforms, and proceed further with
the installation (failing at a different point, which would produce
a harder-to-read error message). This commit fixes things so that
non-supported Mac OSX platforms correctly fail in the osfamily::darwin
class with a readable error message.
> (PA-1887) Fix osfamily::darwin OSX version regex

- .fixtures.yml
- .sync.yml
- Gemfile
- metadata.json
- spec/classes/puppet_agent_osfamily_debian_spec.rb
- spec/spec_helper_acceptance.rb
* Reverts commits not compatible with Puppet 3.8
* Pins dependent modules to Puppet 3.8 compatible versions
* Installs CA certs required on Windows for downloading from the Forge.
> (MODULES-6717) Configure 1.x branch for last 3.8 compatible release

- CHANGELOG.md
- metadata.json
This commit prepares the module for a v1.6.0 release
This is the last release that will be compatible with Puppet 3.x.
> (MODULES-6832) Prepare for v1.6.0 release

- .fixtures.yml
- .sync.yml
- .travis.yml
- CHANGELOG.md
- Gemfile
- README.markdown
- manifests/init.pp
- metadata.json
- spec/classes/puppet_agent_osfamily_debian_spec.rb
- spec/spec_helper_acceptance.rb
- types/arch.pp
This PR
* Merges back 1.x into master
* Un-reverts any commits that were revertted for Puppet 3.8.x support
* Modifies metadata and Travis to drop 3.8
* Update apt to 4.4.0 and remove deprecated functions
Other PRs will come along to extract further Puppet 3.8 functionality
The minimum targetted version is now 4.7.0 (The earliest LTS agent and Puppet 4 Data Types)
> (MODULES-6717) Mergeback 1.x to Master and remove Puppet 3.8

- metadata.json
Previously the Stdlib module was updated in the test fixtures to support the
Puppet 4 types however this was not updated in the metadata.json. (4d9b949df8).
This commit updates the metadata to match that of the minimum test fixtures.
> (maint) Update Stdlib dependency

- manifests/init.pp
- spec/classes/puppet_agent_spec.rb
Prior to this commit, we would manage the puppet-agent version
on any node that was classified with the puppet_agent class.
After this commit, we no check to see if the node is a PE infra
node and if so print a message saying we're not going to do anything
because PE infra nodes have a specific version of puppet-agent
on them for a reason.
You would not, for instance, want your compile master to get its
agent downgraded right after you completed an upgrade of your PE
installation.
> (MODULES-5230) Do not manage PA version on PE infra nodes

- metadata.json
This commit removes Windows Operating Systems that are no longer supported and
adds Server 2016.
> (MODULES-4271) Update Windows OSes in metadata

- spec/acceptance/class_spec.rb
- spec/spec_helper_acceptance.rb
* remove tests around configuration migration as they are not managed by the upgrade
* changed base version from 3.x to 1.7.0 and associated changes
* specified upgrade target as 1.10.0
Three Windows tests are currently red. Two appear to be legitimate failues related to
idempotency. The third is related to service startup.
Tests have only been updated to make things green, with no other refactoring applied
as yet.
> (MODULES-6708) fix tests for windows agent to agent upgrades

- manifests/init.pp
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_osfamily_windows_spec.rb
On FOSS Windows specifically, the agent would continue to upgrade on
every puppet run. This removes a code path that would behave differently
for PE vs. FOSS, and actually perform a version check.
> (MODULES-6915) Remove check for PE when calculating whether to upgrade

- CHANGELOG.md
- metadata.json
This commit prepares the module for a version 1.6.1 release.
Note that this is targetted directly on the `1.x` branch not `release` as the 1.x branch is end-of-life
> (MODULES-7167) Prepare for 1.6.1 release

- manifests/init.pp
- manifests/prepare/package.pp
- spec/classes/puppet_agent_osfamily_aix_spec.rb
For puppet 6, we intend to provide AIX 6.1 packages for all supported
AIX platforms; Prior releases should keep the same behavior for AIX
platforms.
> [MODULES-4195] Install AIX 6.1 RPMs on all AIX versions for puppet6

- manifests/init.pp
- manifests/osfamily/redhat.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
The skip_if_unavailable yum option allows unrelated yum package
management to continue in the event that the agent repository
is unavailble for any reason. It is defaulted to 'absent', which means
the option is not set in the repository file.
> (MODULES-4424) Add skip_if_unavailable to yumrepo resource

- .sync.yml
- .travis.yml
- Gemfile
- manifests/init.pp
- spec/classes/puppet_agent_spec.rb
Previously in commit a658766 the puppet_agent module was changed to not do
anything if ran on a Puppet Master.  However the fact used uses the "newer"
$facts variable which does not exist in Puppet 3.8, which the 1.x series
supports.  This commit changes the fact to the legacy variable name.  Note that
this commit should NOT be merged into the 2.x series as this no longer supports
3.x and therefore is not an issue.  This also updates the test to only work on Puppet 4.x due to the fact
not being mocked correctly in tests.
The other commits relate to re-enabling Puppet 3.x testing and pinning gems due to compatibility issues.
> (MODULES-5230) Use legacy fact variables

- manifests/init.pp
- manifests/params.pp
- spec/classes/puppet_agent_params_spec.rb
- spec/spec_helper.rb
Previously, we'd hardcode the default collection to PC1 in the init.pp
manifest for both PE and non-PE environments. This has a couple of
issues:
* It's impossible to make decisions based on the collection in PE
updates, so as we change package names and paths things get hairy.
* This is already seen with the fedora "f" in Puppet 6, and will soon be
seen with the AIX unibuild
* In Irving.3, we switched to correctly shipping "puppet5" repos instead
of "PC1". This means the module now MUST be aware of how PE versions
map to collections.
This commit calculates the collection default in params.pp using the
following logic
* If we are in a non-PE environment OR our pe_version < 2018.1.3, use PC1
* Else if 2018.1.3 <= pe_version < 2018.2, use puppet5
* Else use puppet6 (pe_version >= 2018.2 …
> (MODULES-7480) Set default collection in params.pp using PE version

- .sync.yml
- Gemfile
The bug that necessitated the pinning (rodjek/rspec-puppet#663) has been
resolved and this module can return to tracking the latest versions of
rspec-puppet again.
> (PDK-1036) Unpin rspec-puppet from 2.6.9

- manifests/install.pp
This commit removes the f that has typically come between the platform name and
version for fedora platforms, e.g. fedoraf25 -> fedora25.
> (CPR-409) Ensure PL projects can handle fedora without the f prefix

- Gemfile
- task_spec/spec/acceptance/init_spec.rb
- task_spec/spec/acceptance/nodesets/osx1011-64.yml
- task_spec/spec/acceptance/nodesets/osx1012-64.yml
- task_spec/spec/acceptance/nodesets/osx1013-64.yml
- tasks/install_shell.sh
Support puppet-agent install on osx 11,12,13. Logic is based on https://github.com/puppetlabs/puppetlabs-pe_repo/blob/hoyt/templates/osx.bash.erb#L5
> (BOLT-702) Install puppet agent on osx

- Gemfile
Add back dependencies we need that were removed in Beaker 4.
> (maint) Restore correct dependencies with Beaker 4

- task_spec/spec/acceptance/init_spec.rb
- task_spec/spec/acceptance/nodesets/windows10ent-32.yml
- task_spec/spec/acceptance/nodesets/windows10ent-64.yml
- tasks/install.json
- tasks/install_powershell.ps1
Add powershell task implementation to install puppet agent on windows platforms. Logic based on https://github.com/puppetlabs/puppetlabs-pe_repo/blob/hoyt/templates/install.ps1.erb
> (BOLT-703) Install puppet agent on windows

- task_spec/spec/acceptance/init_spec.rb
- tasks/install.json
- tasks/install_powershell.ps1
- tasks/install_shell.sh
Adds a collections parameter that defaults to 'puppet'. Available values
- 'puppet5'
- 'puppet6', for future support when it's released
- 'puppet', aliases to the latest available collection
Install will select either the latest version from that collection, or
only work if you provide a valid version within that collection. To
install versions outside the default collection you'll need to
explicitly specify the collection and version.
> (BOLT-742) Add support for collections to install task

- Gemfile
- spec/spec_helper_acceptance.rb
As of beaker 4.0 beaker no longer requires beaker-puppet. This commit adds beaker-puppet required for acceptance tests.
> (maint) Require beaker-puppet for beaker 4.0 update

- Gemfile
- spec/spec_helper_acceptance.rb
This commit pins beaker-rspec at 6.2.3. This forces beaker to be pre 4.0.0. The combination of beaker 4.0.0 and beaker-puppet causes failures in acceptance tests tracked with https://tickets.puppetlabs.com/browse/BKR-1516.
> (maint) Revert to beaker 3.x.x

- Gemfile
In order to support automated testing for install_agent tasks beaker-task_helper was updated to add support for the abs hypervisor.
> (maint) Bump beaker-task_helper version

- task_spec/spec/acceptance/init_spec.rb
- task_spec/spec/acceptance/nodesets/sles11-64.yml
- task_spec/spec/acceptance/nodesets/sles12-64.yml
- tasks/install_shell.sh
This commit adds logic to the install_shell.sh install task implementation to support installing puppet-agent on SLES platforms. Currently the supported platform versions are 11 and 12. Nodeset templates have been added for manual testing.
> (MOD-7655) SLES support for install_agent tasks

- Gemfile
Bolt 0.21.8 includes update to host-key-check that is required by task acceptance tests. This commit updates the bolt dependency accordingly.
> (maint) Update to Bolt 0.21.8

- manifests/install.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
There were some recent changes made to remove the 'f' prefix for our
older Fedora platforms, specifically Fedora 26 and 27. However, this
inadvertently changed our distro tag for these platforms to also remove
the 'f' prefix so that e.g. fedoraf26 became fedora26. This change was not
carried over to the puppet_agent module. Furthermore, newer Fedora
platforms like Fedora 28 use the newer fc<major_version> distro tag
for the puppet5 collection. The puppet_agent module was also not
updated with this change. Thus, some agent upgrades were failing on our
Fedora platforms.
This commit updates the puppet_agent module to handle all possible cases
of the distro tag for our Fedora platforms.
> (MODULES-7758) Properly handle distro tag for Fedora platforms

- task_spec/spec/acceptance/init_spec.rb
- task_spec/spec/acceptance/nodesets/docker/ubuntu-18.04.yml
- tasks/install_powershell.ps1
- tasks/install_shell.sh
When the install_shell.sh implementation is used to install an agent from the puppet5 collection package managment for debian based systems (notibly ubuntu) fail to install puppet-agent from puppet6 collection. This commit allows upgrade from puppet5 to puppet6.
> (BOLT-834) Allow upgrade from puppet5 to puppet6 for install task

- tasks/install_shell.sh
The tasks acceptance tests will install puppet-agent 5.5.3 from the `puppet5` collection by setting both the `collection` and `version` task parameters. Then the task is run again with only the `collection` parameter set to `puppet5` with the expectation that the latest version from the collection will be installed. For fedora 26 when `yum install puppet-agent` was run the upgrade happened as expected. For fedora 27 yum must explicitly upgrade puppet agent in order to have the desired result.
> (maint) Explicitly upgrade when version is not specified for yum

- tasks/install_shell.sh
There is not a good way to make sure a non-root user is installed on test images which makes this hard to test. I've manually tested on:
centos7
fedora 28
debian8
ubuntu-1804
sles 12
osx 10.13
>  (BOLT-878) Fail fast when run as non-root

- manifests/windows/install.pp
Correct URLs for windows msis (Puppet 5 and 6)
> (MODULES-8086) Puppet 5 and 6: wrong urls for windows msi

- Gemfile
- README.markdown
- task_spec/.fixtures.yml
- task_spec/spec/spec_helper_acceptance.rb
- tasks/install.json
- tasks/install_shell.sh
Much of the puppet_agent task is logic to determine the operating systems and version of the target. This is duplicated by the shell implementation of the facts task. The addition of multi-file task support allows using the facts module bash.sh implementation code. The bash.sh implementation has been modified to return platform and version when environment variables PLATFORM=TRUE or RELEASE=TRUE are set. This commit utilizes the code in the facts module to determine platform and version.
> (BOLT-915) Use facts module to query for target platform

- spec/spec_helper_acceptance.rb
Since activemq packages are currently only available in our legacy
dependencies repo, install the legacy puppetlabs-release package.
> (maint) Use legacy dependencies repo for activemq

- Gemfile
Acceptance tests in 1.x are not yet compatible with beaker 4; specify beaker ~> 3 in the Gemfile instead of >= 3.
> (MODULES-8198) Use beaker ~> 3

- manifests/install.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_spec.rb
The dist_tag variable was introduced as a workaround for
PUP-5802/PUP-5025. These tickets were resolved two years
ago, so the workaround is no longer necessary.
>  (MODULES-7760) Remove dist_tag in install.pp for RHEL platforms

- .fixtures.yml
- Gemfile
There are two commits here, both of which are updates to dependencies:
- Update rspec-puppet (2.6.9 to 2.7.2)
- Add yumrepo_core as a fixture to support running spec tests with puppet 6 gems (which can't manage yumrepo resources without the module)
> (MODULES-8318) Update rspec-puppet, add yumrepo_core fixtures for puppet 6

- .travis.yml
- tasks/install_powershell.json
- tasks/install_shell.json
- tasks/version.json
- tasks/version_powershell.json
- tasks/version_shell.json
Adds task metadata required to publish to the Forge. Also declare
input_method where it would use the default `both` and hide extra
implementations for task runners that implement private tasks and task
implementations.
> (MODULES-8393) Add task required metadata, hide extra implementations

- manifests/osfamily/aix.pp
- manifests/osfamily/darwin.pp
- manifests/osfamily/solaris.pp
- manifests/osfamily/suse.pp
- spec/classes/puppet_agent_osfamily_aix_spec.rb
- spec/classes/puppet_agent_osfamily_darwin_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
- spec/classes/puppet_agent_prepare_spec.rb
Previously, macOS upgrades (which are supported only under PE) would
fail silently outside of PE. This adds an error message for that case
and updates other PE-only platforms so that they have consistent error
messages for FOSS installations.
> (MODULES-8446) Improve error messages for PE-only platforms

- files/solaris_start_puppet.sh
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- manifests/service.pp
- manifests/windows/install.pp
- spec/classes/puppet_agent_spec.rb
- templates/install_puppet.bat.erb
- templates/solaris_install.sh.erb
When attempting to upgrade to or within the puppet 6 series in an open
source context (that is, only outside of PE), the module was still
attempting to restart the mcollective servicte after the upgrade -- but
mcollective was removed in puppet 6.
This updates the agent class params so that they find an accurate list
of the services to restart under FOSS.
> (MODULES-8443) Don't restart mco for FOSS puppet6 upgrades

- Gemfile
- task_spec/.fixtures.yml
- task_spec/Rakefile
Previously bolt was pinned back to 1.1.x due to an issue in https://github.com/puppetlabs/bolt/pull/824 which was fixed in 1.9.0. There has also been a new release in the facts module we would like to be testing with. Finally the task acceptance test invocation has been modified to be more succinct and to match other modules that use conditionally require bolt to test module content.
> (maint) Update task_acceptance tests to use updated dependencies

- tasks/install_powershell.ps1
Prior to this fix, we were getting things from the HTTP endpoint, which
had the possibility of a man-in-the-middle attack. This closes that.
> (FM-7656) Use the HTTPS endpoint to fetch puppet-agent MSI files.

- .gitignore
- acceptance/Gemfile
- acceptance/README.md
- acceptance/Rakefile
- acceptance/files/uninstall.ps1
- acceptance/helpers.rb
- acceptance/options.rb
- acceptance/pre_suite/00_master_setup.rb
- acceptance/tests/test_upgrade_pc1_to_puppet5.rb
- acceptance/tests/test_upgrade_puppet5_to_puppet6.rb
Adds an acceptance directory containing a set of scaffold test files
and helpers to allow for testing this module with beaker-puppet instead
of beaker-puppet_install_helper (which is no longer supported). The
README in the acceptance directory describes how to run the new tests.
This leaves the existing tests in spec/acceptance intact for now; in the
future these old tests will either be migrated to the acceptance
directory, or (if they test puppet 3 functionality) removed.
Take note that this process will also eventually remove beaker-rspec,
since it is incompatible with the use of subcommands in beaker 4.
Do not merge until https://github.com/puppetlabs/beaker-puppet/pull/97 has been merged and released. I will need to update the beaker version in the Gemfile once that happens to …
> (MODULES-8348) Acceptance scaffold with beaker-puppet

- manifests/windows/install.pp
The windows provider only runs bare commands, which means an embedded pipe
will be seen as a command parameter and not a pipe. This change adds a cmd
shell as the primary command such that piping, etc. will work as expected.
> (MODULES-8406) fix the broken unless check for inherited permissions

- README.markdown
- acceptance/helpers.rb
- manifests/service.pp
Since we removed the mcollective service in puppet6 collections, we need to update the services management to not attempt to start mco after upgrade.
> (MODULES-8319) Update service to exclude MCO for puppet > 6

- templates/install_puppet.ps1.erb
Since the MSI installer already preserves the environment of an existing
agent install, there's no need to specify it. Additionally, when there is
no 'environment' key present in puppet.conf, this would set the environment
key to the default value 'production', which can cause nodes to be
incorrectly classified after upgrades.
> (MODULES-4730) Do not pass the agent environment during MSI installs

- tasks/install_shell.sh
This commit updates the install_shell task implementation to use https endpoints when downloading puppet-agent packages. Previously the http endpoints were used.
> (FM-7732) Download puppet-agent packages over https

- acceptance/helpers.rb
- acceptance/pre_suite/00_master_setup.rb
- acceptance/tests/test_upgrade_pc1_to_puppet5.rb
- acceptance/tests/test_upgrade_puppet5_to_puppet6.rb
Currently, the update testing in the acceptance directory does not
test by waiting for pidfiles during installations. For
MacOS/Solaris/Windows this means the acceptance tests will not work,
since those platforms will spawn scripts to perform installations
outside of an agent run
So this commit updates the acceptance testing to include waiting for
pidfiles after the puppet run completes so the testing will wait for
the full installation.
There were a few larger refactors done to help facilitate the changes:
1. new functions for waiting for puppet to finish and waiting on
installation PIDs
2. the actual execution of puppet to perform the upgrade now consists
of turning on the puppet service rather than executing 'puppet agent
-t'. This is the approach we use when testing upgrades in PE and …
> (MODULES-5535) Update test matrix to work with MacOS/Solaris/Windows

- docker/bin/helpers/run-upgrade.sh
- docker/bin/upgrade.sh
- docker/bin/versions.sh
- docker/centos/Dockerfile
- docker/centos/Dockerfile.versions
- docker/deploy.pp
- docker/ubuntu/Dockerfile
- docker/ubuntu/Dockerfile.versions
- docker/upgrade.pp
This commit decreases the feedback cycle time to enable iterative
development. The gist is that a developer can use Docker to test out
upgrades on a machine.
The `docker/bin/upgrade.sh [<PLATFORM>] [<BEFORE>] [<AFTER>]`
command builds a container on the `<PLATFORM>` platform that has the
`<BEFORE>` version of puppet on it and adds the `puppet_agent`
module. It then runs `puppet apply` in the container such that the
`<AFTER>` version of puppet exists afterward. This script ends with
a shell inside the container.
Available platforms are Ubuntu Xenial (`ubuntu`) and CentOS 7
(`centos`).
Also available is `docker/bin/versions.sh [<PLATFORM>]`, which will
output which versions of puppet are available on a given
`<PLATFORM>`.
For full details, see docker/ubuntu/Dockerfile or …
> (PA-2282) Add Docker workflow for iterative development

- manifests/osfamily/redhat.pp
- manifests/osfamily/suse.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
SLES 15 uses gpg 2.2, which changed some of its key output formatting
and is noisier about missing commands. This change normalizes the text
parsing of gpg keys, using the --with-colons option, that is recommended
in the man page for use in scripts. The updated parsing pipelines work with
older and newer versions of gpg.
> (MODULES-8583) Improve rpm importing of the puppet GPG key

- task_spec/spec/acceptance/init_spec.rb
Previously, the tests were omitting the `params` argument to `run_task`.
In newer versions of BoltSpec, that parameter is going to be required,
so now we always pass it.
> (BOLT-1057) Pass required args to run_task

- templates/install_puppet.ps1.erb
We have seen cases with customers where after shutting down the pxp-agent
service there are still pxp-agent processes open.
This commit adds a workaround to the install_puppet.ps1 powershell script to
wait for any open pxp-agent processes to close, and if they don't the upgrade
script will stop before actually attempting the upgrade.
> (FM-7628) Update install_puppet.ps1 to catch hanging pxp-agent processes

- README.markdown
Various improvments to include details related to newer Puppet package
repos and other minor clarifications.
Removed a reference about upgrading to Puppet 4, which is no longer
supported - Puppet 4 is the baseline version you can use this module to
upgrade from.
> (MODULES-4780) README improvements

- lib/facter/settings.rb
- manifests/osfamily/debian.pp
- manifests/osfamily/redhat.pp
- manifests/osfamily/suse.pp
- spec/classes/puppet_agent_osfamily_debian_spec.rb
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
In environments with multiple compile masters behind a load balancer,
using `$::servername` could cause Puppet to constantly update the repo
configuration based on the compile master that happens to be compiling
the catalog at that time.
Changing the value to `$::puppet_master_server` uses the server value in
puppet.conf, which in most (all?) cases should be the load balanced point.
> Fix unnecessary changes in load balanced envs due to pkg source

- README.markdown
- acceptance/pre_suite/00_master_setup.rb
- manifests/init.pp
- manifests/install.pp
- manifests/install/darwin.pp
- manifests/install/solaris.pp
- manifests/install/windows.pp
- manifests/osfamily/aix.pp
- manifests/osfamily/darwin.pp
- manifests/osfamily/debian.pp
- manifests/osfamily/redhat.pp
- manifests/osfamily/solaris.pp
- manifests/osfamily/suse.pp
- manifests/osfamily/windows.pp
- spec/classes/puppet_agent_osfamily_aix_spec.rb
- spec/classes/puppet_agent_osfamily_darwin_spec.rb
- spec/classes/puppet_agent_osfamily_debian_spec.rb
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
- spec/classes/puppet_agent_windows_install_spec.rb
- tasks/install.json
- tasks/install_powershell.json
- tasks/install_powershell.ps1
- tasks/install_shell.json
- tasks/install_shell.sh
This commit adds new source parameters:
* absolute_source
* yum_source
* apt_source
* mac_source
* windows_source
* solaris_source
* aix_source
* use_alternate_sources
* alternate_master_source
Each source parameter will modify where the module attempts to pull packages
for different use cases.
Absolute_source: This parameter is for use cases where the package source
should be an absolute path on the filesystem. It's a common windows paradigm
to use a network share to serve files to systems behind a firewall. This param
should server that purpose.
(yum/apt/mac etc.)_source: these parameters are for use cases where someone has
mirrored the public downloads sites for puppet and they just need to change the
underlying base URL for grabbing packages. Hopefully this enables workflows
like …
> (MODULES-6604) Add new source parameters

- files/install_puppet.ps1
The windows installer uses the puppet command from the CLI to find the
statedir to put install state files in. When the default environment for
puppet is set to something other than production the command fails on older
agents (See: https://tickets.puppetlabs.com/browse/PUP-6739).
This commit simply updates the invocation of the puppet command to force the
production environment when finding the statedir.
> (MODULES-8821) Update win install to use production environment

- docker/centos/Dockerfile
- docker/centos/Dockerfile.versions
- tasks/install_shell.sh
The location of public release packages will change on May 14. As such, the following changes aim to prepare for the changeover to ensure there are no breakages with downstream dependencies.
> (RE-12326) Changes to public release package links

- README.markdown
The example for `aix_source` uses `solaris_source`. Fix this example.
> (docs) Fix bad aix_source example.

- manifests/osfamily/redhat.pp
Currently, if you have a RedHat-based machine and you specify the **PC1** collection, you get a yum repository configuration with the `source` set to:
http://yum.puppet.com/PC1/el/6/x86_64
However, the correct URL should be:
http://yum.puppet.com/el/6/PC1/x86_64
This PR fixes the `source` to use the correct URL if **PC1** is the collection being used.
> Fix Yum URL path for RedHat systems still using the PC1 collection

- Gemfile
- task_spec/Rakefile
- task_spec/spec/acceptance/init_spec.rb
- task_spec/spec/spec_helper_acceptance.rb
This commit updates the task acceptance tests to use appropriate puppet-agent versions to install and upgrade from the puppet 5 collection. It also utilizes new a new feature in the BoltSpec::Run module allowing bolt configuration to occur outside of individual method calls.
> (maint) Fix task acceptance tests for fedora 29

- manifests/init.pp
- manifests/osfamily/aix.pp
- manifests/osfamily/darwin.pp
- manifests/osfamily/suse.pp
- manifests/osfamily/windows.pp
- spec/classes/puppet_agent_osfamily_aix_spec.rb
- spec/classes/puppet_agent_osfamily_darwin_spec.rb
- spec/classes/puppet_agent_osfamily_windows_spec.rb
- spec/classes/puppet_agent_spec.rb
With this commit, the user can specify `package_version` as 'master'
to specify that the package version should be the same as the compiling master.
> (MODULES-8923) autodetect package_version based upon the master

- manifests/params.pp
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- templates/solaris_install.sh.erb
This PR fixes the following:
When and upgrade is done for solaris 10 we enable the service only if the service was running before.
> (MODULES-9173) Mcollective service restarting when PA upgrade is done.

- README.markdown
v2.1.0 added macOS support. Revise the note under "Limitations" to acknowledge this.
> (docs) Revise macOS limitations note.

- README.markdown
Clarity between release names "Puppet 6" and class parameters "puppet6"
Additional PSA regarding older releases supporting upgrading of Puppet 3 to Puppet 4; It is still a thing in the field, so a helpful pointer shouldn't go amiss.
> Readme naming consistency

- .fixtures.yml
- metadata.json
- task_spec/.fixtures.yml
This commit adds the puppetlabs-facts module to the dependency list of
puppetlabs-puppet_agent. Tasks from the facts module are required by
the puppet_agent::install task.
> (MODULES-8665) Add missing puppetlabs-facts dependency

- .fixtures.yml
- .travis.yml
- metadata.json
A number of modules are now allowing stdlib 6.x and we expect some will require it. It would be great to get a new release after this PR so that a version of puppet_agent is available supporting stdlib 6.x. Thanks.
> (maint) Allow stdlib 6.x

- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- task_spec/spec/acceptance/init_spec.rb
To ensure Task Acceptance Tests pass with Fedora 30 we need to add the available puppet5 version:
```
[root@pogb5jjn91gy53y ~]# yum repoquery -a --repoid=puppet5
Puppet 5 Repository fedora 30 - x86_64                                                                                     
puppet-agent-0:5.5.16-1.fc30.x86_64
puppet-bolt-0:1.24.0-1.fc30.x86_64
puppet-bolt-0:1.25.0-1.fc30.x86_64
puppet-bolt-0:1.26.0-1.fc30.x86_64
puppet5-release-0:5.0.0-7.fc30.noarch
```
> (PE-26530) Update spec and task acceptance tests with Fedora 30

- files/install_puppet.ps1
When a agent upgrade fails for some reason, the
puppet_agent_upgrade.pid file is not deleted, and the next time
the install_puppet.ps1 runs, it fails again and again as it cannot start
the installation because of the stale .pid file.
Now, the install_puppet.ps1 checks if the PID inside the .pid file is
still running, and if not, it will replace the PID inside the file and
continue the installation.
> (MODULES-9497) install_puppet.ps1 stale .pid file

- task_spec/.fixtures.yml
Update the version of puppetlabs-facts to match what is shipped with the latest bolt version.
> (MODULES-9698) Update facts module used for testing install task

- manifests/install/windows.pp
- spec/classes/puppet_agent_windows_install_spec.rb
In case a cached catalog requesting puppet agent installation is
applied, the install script executes msi install and service
restart each time is run.
With this correction, the puppet agent package version is checked
against aio_agent_version fact and install continues only if
there is no match.
> (MODULES-9846) fix install using cached catalog

- task_spec/spec/acceptance/init_spec.rb
- tasks/install.json
- tasks/install_powershell.json
- tasks/install_powershell.ps1
- tasks/install_shell.json
- tasks/install_shell.sh
This adds a parameter to the `puppet_agent::install` task that, when
true, will stop the puppet service after install. The parameter defaults
to false. The option is available for both unix and windows platforms
> (GH-1204) Add option to stop the puppet agent service after install

- spec/classes/puppet_agent_spec.rb
This test was failing due to some changes on
rspec-expectactions gems.
More info here: https://github.com/rspec/rspec-expectations/issues/1134
> (maint) fix failing tests due to rspec changes

- README.markdown
- tasks/install_shell.sh
This adds Amazon Linux 2 support in tasks/install_shell.sh. Tested
manually on Amazon Linux 2.
> (MODULES-9981) Add Amazon Linux 2 support

- tasks/install_powershell.ps1
This commit fixes the path from where to download puppet-agent if the
requested collections is a nightly build.
If the windows_source is explicitly specified as a parameter, it will
use it instead.
> (MODULES-10038) nightly build download location fix

- README.markdown
- files/install_puppet.ps1
- manifests/init.pp
- manifests/install/windows.pp
- spec/classes/puppet_agent_windows_install_spec.rb
Changing WaitForExit value to 8 minutes (42000 ms) versus 2 minutes (120000 ms). 
Additional time for the pxp-agent.exe processes to end successfully. Have experienced issues where the process doesn't end in 2 minutes causing the upgrade installation to fail.
> (MODULES-10052) parameterize WaitForExit timeout in puppet_agent install script

- manifests/osfamily/windows.pp
- spec/classes/puppet_agent_osfamily_windows_spec.rb
- spec/spec_helper_local.rb
This commit ensures that the correct version of puppet agent is
installed on windows platforms that are FIPS compliant based on the
enabled_fips fact.
> (MODULES-27043) Puppet agent upgrade for windows FIPS

- tasks/install_shell.sh
This updates the install task to allow for downgrading the Puppet agent
when installing with `apt`. This aligns the behavior of the task with
other package handlers, such as `rpm`, that allow for downgrading the
Puppet agent version.
Part of https://github.com/puppetlabs/bolt/issues/1208
> (MODULES-10308) Allow downgrades when using apt

- spec/classes/puppet_agent_spec.rb
rspec-puppet-facts added a new feature that discovers
the facter data that needs to get from facterdb based on
agent version. Because Solaris tests rely on `puppet_agent_pid`
fact which changed between facter version from facterdb, tests were
unreliable.
This commit explicitly sets `puppet_agent_pid` on Solaris.
> (maint) fix Solaris tests

- task_spec/spec/acceptance/init_spec.rb
- tasks/install.json
- tasks/install_powershell.json
- tasks/install_powershell.ps1
- tasks/install_shell.sh
This modifies the behavior of the `puppet_agent::install` task so that
it only assumes that the latest version of the agent should be installed
when no agent is present on the system. Previously, if the `version`
parameter was undefined, the task would default to the latest version
and install it on the system, even if an agent was already present. This
would clobber any existing version of the agent, even unintentionally.
Part of puppetlabs/bolt#1208
> (MODULES-10454) Install 'latest' only when no agent is present

- README.markdown
- tasks/install.json
This updates the documentation for the `puppet_agent` tasks in
`README.md` and the description for the `value` parameter in the
`puppet_agent::install` task.
Part of puppetlabs/bolt#1208
> (MODULES-10477) Update task documentation

- tasks/install.json
- tasks/install_powershell.json
- tasks/install_powershell.ps1
This removes the use of the `version_powershell` task in the
`install_powershell` task. Previously, this task was used to determine
whether the `puppet-agent` package was already installed. However, some
features used to run the script and parse its output are not available
in versions of powershell older than 3.0.
The `install_powershell` task instead uses behavior similar to the
`version_powershell` task by checking the system's registry entries to
check if the `puppet-agent` package is installed.
> (MODULES-10514) Remove use of version_powershell task in install task

- bolt_plugin.json
The `config` field in a plugin's `bolt_plugin.json` file is deprecated
in Bolt 2.0 This removes the field from the `puppet_agent` plugin so it
does not raise an error.
Part of puppetlabs/bolt#1598
> (maint) Remove config field from bolt_plugin.json

- tasks/install_shell.sh
This updates the `install_shell` task to check whether the configuration
file `/etc/apt/repos.list.d/puppet.list` has been modified prior to
installing the `puppet-release` repo.
Previously, if a user had modified the file (such as by manually
maintaining the repo), `dpkg` would prompt the user whether they wanted
to keep the old config file or replace it with the maintainer's config
file. This caused the script to stall as it waited for user input. While
`dpkg` can answer these prompts non-interactively using the
`--force-conf*` options, this behavior would be undesirable as it could
result in the script making a critical decision for the user. Instead,
the script will provide a helpful warning that the config file has been
modified and that agent installation will be skipped.
Closes …
> (MODULES-10589) Exit early when puppet.list config file has been modified

- manifests/osfamily/redhat.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
Since the rhel macro from RPM reports Amazon Linux 2 as being RedHat 7:
```
[root@[redacted] ~]# rpm -E %{rhel}
--
7
```
This PR updates the pc_repo used for Amazon Linux 2 from el-6 to el-7
> (MODULES-10110) Handle Amazon Linux 2 as el-7

- files/install_puppet.ps1
If one of the services managed by this module cannot be started, an error is thrown and the pidlock file is not removed.
This PR  makes sure the error is logged in a format similar to the other exceptions and that the pidlock file is removed in case of a Set-Service failure.
> (MODULES-10594) Remove pidlock if service states cannot be restored

- metadata.json
A prior change ensured that puppet_agent didn't use inifile version 3.2.0. That version comparison seems to have been preserved when moving to any 3.x version in a non-sensical way (allowing 4.0.0 but not anything later). Switch to allowing all versions prior to an unreleased breaking 5.0 version.
> (packaging) Update inifile dependency to allow all 4.x versions

- tasks/install_shell.sh
As `bolt` only [collects](https://puppet.com/docs/bolt/latest/applying_manifest_blocks.html#how-manifest-blocks-are-applied) custom facts in `apply_prep` task, which first [makes](https://github.com/puppetlabs/bolt/blob/master/bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb#L109) sure that the agent is installed, failing fast makes it impossible to gather custom facts when running as non-root even if the agent is already installed.
> Check that user is root only if installation is required

- task_spec/spec/acceptance/init_spec.rb
Change versions to upgrade from for OS X 10.14 and 10.15.
OS X 10.15 should be enabled in CI after puppet 5.5.20 is released, so it would have a version to upgrade from.
> (maint) Fix task acceptance for osx 10.14 & 10.15

- tasks/install_shell.sh
Add condintion to allow downloading puppet agent packages from 10.15 repo.
> (maint) Allow install task to downlad macos 10.15

- README.markdown
Upgrading windows agents using the regular install task definitely doesn't work.
It might work for linux nodes but without testing that doesn't seem advisable.
> (MODULES-10633) Don't use the install task for upgrades

- manifests/service.pp
mcollective was being inappropriately left as a default service to manage. Issue seems to be occurring, because `collection` is not being defined on OSS installations: https://github.com/puppetlabs/puppetlabs-puppet_agent/blob/master/manifests/params.pp#L50
This was resulting with the following error, when `service_names` parameter was not explicitly defined as a parameter
> change from 'stopped' to 'running' failed: Systemd start for mcollective failed!
> (MODULES-10636) Fixed mcollective being included as a default service to manage, in clientversion >= 6.0.0

- metadata.json
- spec/classes/puppet_agent_osfamily_darwin_spec.rb
Tested with PE by upgrading from agent version 6.13.0 to 6.15.0.
> (MODULES-10661) Add OS X 10.15 support

- tasks/install_shell.sh
This adds Ubuntu 20.04 as a supported platform to the
`puppet_agent::install` task.
> (MODULE-10662) Add Ubuntu 20.04 to puppet_agent::install task

- metadata.json
puppetlabs-puppet_agent module required a puppetlabs-facts
version <1.0.0, which caused a warning as puppetlabs-facts is now at
version 1.0.0.
Removed the upper limit on version requirements for puppetlabs-facts.
> (MODULES-10673) Update dependency for puppetlabs-facts

- task_spec/spec/acceptance/init_spec.rb
- tasks/install_powershell.ps1
Before this commit, when trying to run the `puppet_agent::install_powershell` task, with a specific version as parameter, it was failing with below error message:
> Error: Timed out waiting for status response from <node_name>
On the node, both `puppet agent` and `pxp-agent` services got stopped and the event log viewer showed:
> Application or service 'task_wrapper' could not be shut down.
Due to Windows agents becoming unresponsive when running this task and as per [MODULES-10633](https://tickets.puppetlabs.com/browse/MODULES-10633) discussions, the `puppet_agent::install_poweshell` task should not be used for upgrading Puppet Agents while either of`puppet agent` or `pxp-agent` services are still running. This Puppet Agent module task will now fail immediately and output a message if …
> (MODULES-10653) Failed to upgrade agent using puppet task

- README.markdown
- lib/puppet/provider/puppet_agent_end_run/puppet_agent_end_run.rb
- lib/puppet/type/puppet_agent_end_run.rb
- manifests/install.pp
- manifests/install/solaris.pp
- spec/acceptance/class_spec.rb
Previously, when evaluating additional resources after a puppet-agent
upgrade, we could get to a point where we had a mixture of old/new
Ruby code loaded in memory. This may cause unexpected behavior if the
new code tries to execute something not available in the already
loaded old code.
This commit introduces a new type/provider that is evaluated whenever
a puppet-agent upgrade happens on a platform managed with the package
resource (AIX, Debian, EL, Suse).
The newly added resource attempts to figure out if a Puppet upgrade
was performed, then stops the run altogether. If Puppet is being run
as a service, the HUP signal will have the daemon trigger a subsequent
Puppet run that will evaluate the remaining resources.
When running `puppet agent -t` manually, it is up to the user to rerun …
> (MODULES-10666) Stop agent run after an upgrade

- manifests/install.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
This fix will make sure then on RedHat like kernels, the `package_version` is used to determine if the agent should be downgraded or upgraded  when when using `absolute_source` parameter.
> (MODULES-10655) Fix up/downgrade of agent to specified version

- CHANGELOG.md
- metadata.json
We've chosen to do a major release due to the significant changes
brought on by MODULES-10666.
See: https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/496
> (MODULES-10695) Release prep for 4.0.0

- lib/puppet/provider/puppet_agent_end_run/puppet_agent_end_run.rb
- manifests/install.pp
- manifests/install/solaris.pp
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_spec.rb
Due to Solaris p5p limitations, we munge dev build versions by stripping all letters (i.e.: 5.5.20.102.g9e5216a6 turns to 5.5.20.102.952166).
This causes `Gem::Version` to wrongly interpret the desired version on Solaris 11, making upgrades not idempotent.
Use a regex instead of `Gem::Version` to make `package_version` more like the `aio_agent_version` fact. Move this logic from the provider to the Puppet manifests in order to be able to properly spec test this.
> (MODULES-10713) Fix agent upgrade on Solaris 11

- README.markdown
- plans/run.pp
- tasks/run.json
- tasks/run.rb
This adds a new `puppet_agent::run` task that runs the Puppet agent on a
list of targets, and returns the run report contents as well as the
exit code for the agent run.
This also adds a `puppet_agent::run` plan which checks if the agent is
installed on each target and runs the `puppet_agent::run` task on each
target that has the agent installed. The plan returns a `ResultSet` that
includes fail results for targets that do not have the agent installed,
as well as the results from the `puppet_agent::run` task.
> (MODULES-10768) Add task and plan for running Puppet agent

- acceptance/tests/test_upgrade_puppet6_to_puppet7.rb
This PR tests the upgradability to puppet 7 using the
puppetlabs-puppet_agent module.
Currently it uses the puppet 7 nightly builds, as a puppet7 collection
does not exist.
> (MODULES-10780) PA 6 to PA 7 upgrade tests

- spec/acceptance/class_spec.rb
- spec/spec_helper_acceptance.rb
The first release that included support for `Fedora 30` was Puppet Agent version `5.5.16`. Before this commit, the tests were using `5.5.14`.
Test teardown for SLES wasn't removing `pc_repo.repo`, causing unwanted Puppet Agent version installations.
> (maint) Bump puppet agent version used in acceptance tests and fix them

- lib/facter/settings.rb
- lib/puppet/functions/any_resources_of_type.rb
- manifests/init.pp
- spec/classes/puppet_agent_spec.rb
- spec/unit/facter/settings_spec.rb
- spec/unit/functions/any_resources_of_type_spec.rb
Puppet 7 changed the default digest algorithm to SHA256 in
https://github.com/puppetlabs/puppet/pull/8325. This could cause
failures when upgrading if remote filebuckets are also enabled.
Before performing the upgrade, check if remote filebuckets are enabled
and compare the digest algorithms of the agent/server. If they differ,
abort the upgrade.
> (MODULES-10799) Ensure upgradability from puppet 6 to 7 when remote filebuckets are enabled

- .github/workflows/daily_unit_tests_with_nightly_puppet_gem.yaml
- .github/workflows/static_code_analysis.yaml
- .github/workflows/unit_tests_with_nightly_puppet_gem.yaml
- .github/workflows/unit_tests_with_released_puppet_gem.yaml
- Rakefile
The `commits` rake task was failing due to the recent branch renaming (master->main) and the GitHub Actions Static Code Analysis job was fetching only the HEAD commit.
Unit tests seem to be running much faster on `Windows 2016` with `GitHub Actions` than `Windows 2019`.
> (maint) Fix commits rake task and speed up unit tests run on Windows GitHub Actions

- files/helpers.ps1
- files/install_puppet.ps1
- files/prerequisites_check.ps1
- manifests/init.pp
- manifests/install.pp
- manifests/install/windows.pp
- spec/classes/puppet_agent_windows_install_spec.rb
When performing a puppet-agent upgrade with PE, the .msi package
that will get downloaded by default is the puppet-agent version
of the server node.
If a different version than the one on the master is requested,
if no pe_repo is configured and available, it will install the version
on the master.
This PR fails if the desired version and version from the .msi match.
If they do not match the install_puppet.ps1 will fail before installing
an unwanted version.
> (MODULES-10813) Mismatched versions stops install

- files/install_puppet.ps1
- files/prerequisites_check.ps1
$PSScriptRoot does not exist in PowerShell versions prior to 3.
This PR determines if this variable exists and if it does not, it sets the value
> (MODULES-10850) determine PSScriptRoot if it does not exist

- files/prerequisites_check.ps1
MODULES-10813 introduced a new powershell script that is executed on every Windows upgrade: `prerequisites_check.ps1`.
This script checks whether the version in the MSI matches what `$package_version` we want to install.
To install a nightly build, the user would pass something like `7.0.0.463.gf7e6640e` to `package_version`. This gets munged by the
puppet_agent module into `7.0.0.463` which is then given to the `prerequisites_check.ps1` script.
It appears that MSI packaging does not discern between released builds and nightly builds, as the versions reported by the MSI package are always of type `MAJOR.MINOR.PATCH`, so the script would compare `7.0.0` with `7.0.0.463`.
Change the script to always strip the commit number from the version when comparing.
> (MODULES-10851) Fix Windows nightly prerequisites check

- Gemfile
The latest release of rspec-expectations changed 
`raise_error` and breaks rspec-puppet: https://github.com/rodjek/rspec-puppet/issues/810
Lock `rspec-expectations < 3.10` until the issue is fixed.
> (maint) use rspec-expectations < 3.10

- .github/workflows/daily_unit_tests_with_nightly_puppet_gem.yaml
- .github/workflows/static_code_analysis.yaml
- .github/workflows/task_acceptance_tests.yaml
- .github/workflows/unit_tests_with_nightly_puppet_gem.yaml
- .github/workflows/unit_tests_with_released_puppet_gem.yaml
Due to unknown environment changes in GitHub Actions runners, we encountered the following error:
`fatal: cannot create directory at 'spec/vcr/GitHubChangelogGenerator_OctoFetcher/_fetch_closed_issues_and_pr/when_API_call_is_valid/returns_pull_request_with_proper_key': Filename too long`
As seen [here](https://github.com/puppetlabs/puppetlabs-cron_core/runs/1378175681?check_suite_focus=true), it was happening when trying to clone https://github.com/skywinder/github-changelog-generator, which indeed has very long paths in [spec folder](https://github.com/skywinder/gitlab-changelog-generator/tree/master/spec/vcr/GitHubChangelogGenerator_OctoFetcher/_fetch_closed_issues_and_pr/when_API_call_is_valid/returns_pull_request_with_proper_key).
This commit allows git to use long paths in our GitHub …
> (maint) Allow git to use long paths in GitHub Actions

- .github/workflows/task_acceptance_tests.yaml
- README.markdown
- acceptance/README.md
- acceptance/helpers.rb
- docker/bin/helpers/run-upgrade.sh
- docker/centos/Dockerfile
- docker/centos/Dockerfile.versions
- docker/ubuntu/Dockerfile
- docker/ubuntu/Dockerfile.versions
- manifests/install/solaris.pp
- manifests/service.pp
- task_spec/spec/acceptance/init_spec.rb
- tasks/install.json
- tasks/install_powershell.json
- tasks/install_shell.json
- tasks/install_shell.sh
This makes it possible to install puppet-agent from the puppet7 collection,
while keeping the current behavior of defaulting to puppet6.
Bump the github action to ruby 2.5 as puppet7 doesn't support earlier versions.
Add `--trace` argument to puppet apply run that performs the upgrade.
> (MODULES-10873) Add support for puppet7 collection

- manifests/osfamily/aix.pp
- spec/classes/puppet_agent_osfamily_aix_spec.rb
As part of deprecating/removing support for AIX 6.1, agent AIX packages have been changed to build on AIX 7.1 instead of 6.1.
Update the puppet_agent upgrade logic to account for these changes.
> (MODULES-10878) Use correct packages when upgrading AIX

- .fixtures.yml
Part of: tickets.puppetlabs.com/browse/PUP-10823
Facter 4 changed how the code from custom facts is evaluated,
this introduced a couple of changes needed for apt module,
more details here: puppetlabs/puppetlabs-apt@6786d50
Bump apt module to 7.4.2 to resolve performance issues when
running unit tests on Linux
This fix reduces the unit tests run on puppet6/ruby 2.5 from 55 minutes to 10 minutes
> (maint) update apt to 7.4.2 for unit tests

- tasks/install_shell.sh
Accidentaly removed the RPM part of the filename when getting the GPG
key for SLES in the install task. This commit adds it back.
> (MODULES-10897) Fix GPG key typo

- tasks/install.json
- tasks/install_powershell.json
- tasks/install_powershell.ps1
- tasks/install_shell.json
- tasks/install_shell.sh
Before this commit, the install tasks (`install_shell.sh` and `install_powershell.ps1`) exited at the first network connectivity failure. This change adds a retry mechanism to the `wget`, `curl`, `fetch`, `perl`, `yum`, `zypper`, `apt-get` (Linux) and `System.Net.Webclient.DownloadFile` (Windows) commands which waits one second between attempts. The number of attempts is `5` by default but can be configured via the new `retry` setting.
> (MODULES-10909) Commands retry on network connectivity failures 

- manifests/install/windows.pp
Add a missing `-ExecutionPolicy bypass` to align with the other PowerShell invocations of the module and unbreak upgrading Puppet on windows.
This seems to be a regression following 9bd01ce0cacdd94ed13310f5b3ac7af5185c0c77, but I only experience the failure on freshly reinstalled windows nodes.  Older nodes seems to have a different default configuration, but it's not something that we change in our setup so I assume the change is on the Microsoft side.
After this change, new windows nodes with an old version of Puppet (7.1.0) can update to the latest version (7.3.0).
> Fix upgrading Puppet on windows

- metadata.json
Bump the upper bound of the module dependencies:
- `puppetlabs-stdlib`: `7.0.0` -> `8.0.0`
- `puppetlabs-inifile`: `5.0.0` -> `6.0.0`
- `puppetlabs-apt`: `8.0.0` -> `9.0.0`
All supported modules (including the three mentioned above) recently had a major release in order to incorporate support for Puppet 7.
> (MAINT) Bump upper bound of module dependencies

- README.markdown
- manifests/configure.pp
- manifests/init.pp
- spec/classes/puppet_agent_configure_spec.rb
- spec/classes/puppet_agent_spec.rb
- spec/type_aliases/config_spec.rb
- types/config.pp
- types/config_setting.pp
I'm proposing this feature as a result of not being able to find a clear, supportable, and documented way to advise a PE customer how to manage agent configuration.
This commit introduces a parameter that can be used to manage agent configuration. This parameter is restricted to managing only specifically permitted settings. Initially, only runinterval.
Without this functionality, users can only manage agent configuration by independently writing their own ini_setting resources in their own code. This is inefficient and error-prone compared to supporting basic configuration management of the agent in the official Puppet agent supported module.
By supporting basic configuration management of settings in this module it will be easier and safer to configure the Puppet agent, as well as …
> (MODULES-10879) Implement configuration management

- README.markdown
- files/install_puppet.ps1
- manifests/init.pp
- manifests/install/windows.pp
- spec/classes/puppet_agent_windows_install_spec.rb
- (Support-42796) Add ```wait_for_puppet_run``` parameter to configure the timeout value for the current puppet run.
Previously, if the puppet agent was to be upgraded but the current run took longer than 120000 ms (2 minutes) to complete, the agent upgrade script (install_puppet.ps1) would fail. This would happen even if the agent run would have otherwise completed without error.
- Fixed ```wait_for_pxp_agent_exit``` parameter tests. The parameter accepts an Int32, but the tests were passing booleans.
> (MODULES-9798) Add Timeout Parameter for the Current Puppet Run

- CHANGELOG.md
- Gemfile
- metadata.json
Update supported platforms in metadata.json, bump version and add changelog.
> (MODULES-10979) Release prep for 4.5.0

- task_spec/spec/acceptance/init_spec.rb
- tasks/install.json
- tasks/install_powershell.json
- tasks/install_shell.json
This removes the puppet5 collection from the list of available sources
for the puppet agent install task, since it's EOL. This also
updates the task spec to use puppet6 for testing and only test upgrading
from puppet 6 to puppet 7, not puppet 5 to puppet 6.
> (MODULES-10989) Remove puppet5 collection

- tasks/facts_diff.json
- tasks/facts_diff.rb
Starting with puppet 6.22.0, `puppet facts diff` supports a new parameter
`--exclude` that allows users to remove certain facts from output
This commit exposes `puppet facts diff` `--exclude` parameter to
`facts_diff` task via `exclude` parameter
> (MODULES-11045) add `exclude` parameter to `facts_diff` task

- tasks/delete_local_filebucket.json
- tasks/delete_local_filebucket.rb
This adds a task that removes the local filebucket
which was disabled by default in Puppet 7.
The location of filebucket is determined using the
`clientbucketdir` puppet config.
```
❯ bolt task show puppet_agent::delete_local_filebucket
puppet_agent::delete_local_filebucket
Removes the local filebucket
Usage
bolt task run puppet_agent::delete_local_filebucket --targets <targets>
[force=<value>]
Parameters
force  Optional[Boolean]
ignore nonexistent files and errors
```
Tested on Windows:
```
$ ls  /cygdrive/c/ProgramData/PuppetLabs/puppet/cache/clientbucket
ls: cannot access /cygdrive/c/ProgramData/PuppetLabs/puppet/cache/clientbucket: No such file or directory
❯ bolt task run puppet_agent::delete_local_filebucket
{"_error"=>{"msg"=>"Errno::ENOENT: No such file or directory @ apply2files …
```
> (MODULES-11048) task to remove local filebucket

- acceptance/helpers.rb
- acceptance/tests/test_upgrade_puppet5_to_puppet6.rb
- acceptance/tests/test_upgrade_puppet6_to_puppet7.rb
- files/rpm_gpg_import_check.sh
- manifests/install.pp
- manifests/install/suse.pp
- manifests/osfamily/redhat.pp
- manifests/osfamily/suse.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
- spec/classes/puppet_agent_spec.rb
SLES 11 can no longer be upgraded in PE by installing from the repos. To work around this, if we're SLES 11 and PE, download the package and install it directly using rpm, regardless of the value of `manage_repo`. This is the same approach we take for AIX, macOS and Windows. Because zypper is left in a semi-broken state if our pe_repo is installed, make sure we remove it and don't install it again.
The GPG keys will continue to be imported.
For non-PE agents, installing from the FOSS repos should still be possible, so nothing should change on that part. Additional tests were added to assert the behavior of FOSS vs PE.
> (MODULES-10996) Fix SLES 11 PE upgrades

- CHANGELOG.md
- metadata.json
- tasks/install.json
- tasks/install_powershell.json
- tasks/install_powershell.ps1
- tasks/install_shell.json
- tasks/install_shell.sh
This enables running the `puppet_agent::install` task in noop mode. When
the task is run in noop mode, it executes up until the puppet-agent
package is downloaded and installed.
This work enables adding support for running plans in noop mode in Bolt,
which uses the `puppet_agent::install` task as the default
puppet_library plugin when running an `apply_prep`.
> (MODULES-11066) Add support for running puppet_agent::install in noop mode

- tasks/facts_diff.rb
Previously, running the `facts_diff` task with its `exclude` argument set to a regular expression with characters considered special in `cmd`/`powershell`/`bash` could end up discarded or injected as part of the underlying `puppet facts diff` CLI command.
This commit ensures that all `cmd`/`powershell`/`bash` special characters are escaped by wrapping the `exclude` regular expression argument content between double quotes and validates it before passing it to the `Puppet::Util::Execution.execute` method. Invalid regular expressions will raise `RegexpError`.
Used ``^!@%\$&(a)d+\w*\.\/|facter|\|d?[a-z]-=<>;:|a{3}|0`~|\(\[\<$|custom`` as a base for testing the exclude argument against special characters. Manual tests passed using CLI, PE console and bolt on both Linux and Windows machines. …
> (MODULES-11074) Fix `facts_diff` task argument parsing on Windows

- manifests/osfamily/darwin.pp
- metadata.json
- spec/classes/puppet_agent_osfamily_darwin_spec.rb
- task_spec/spec/acceptance/init_spec.rb
- tasks/install_shell.sh
Most of the changes are caused by the change in major product version.
Until now, the major product version was 10.15, 10.14, etc.
Starting with MacOS 11, the major version was incremented and we
started to use only the first number (eg. 11) as major version
> (PE-31118) add MacOS 11 support

- task_spec/spec/acceptance/init_spec.rb
task acceptance tests are failing on windows
with a connection timeout. Because of unknow reasons,
running the first remote command takes longer than
the default timeout of 10 seconds.
This commit increases the timeout of winrm hosts
to 120 seconds
> (maint) increase winrm connection timeout

- .github/workflows/task_acceptance_tests.yaml
- Gemfile
- task_spec/spec/acceptance/init_spec.rb
This bumps the minimum Bolt version to 3.0 for acceptance testing.
> (MODULES-11078) Bump Bolt to 3.x

- README.markdown
- manifests/init.pp
- manifests/osfamily/redhat.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
Original description:
> This is to be able to configure yum-repo with proxy, needed for
example for clients in dmz:s that need to use proxy to reach the repo
provided by puppetserver.
This replaces https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/504, I rebased on the latest main, added documentation and a test.
> (MODULES-11112) Add parameter puppet_agent::proxy

- .github/workflows/task_acceptance_tests.yaml
- docker/bin/upgrade.sh
- docker/bin/versions.sh
- docker/rocky/Dockerfile
- docker/rocky/Dockerfile.versions
- spec/acceptance/nodesets/docker/rocky-8.yml
- spec/acceptance/nodesets/rocky-8.yml
- task_spec/spec/acceptance/nodesets/docker/rocky-8.yml
- task_spec/spec/acceptance/nodesets/rocky-8-x64.yml
- tasks/install_shell.sh
When running the puppet_agent::install task on a Rocky Linux target, the following message appears :
20:24:31 +0000 INFO: Version parameter not defined and no agent detected. Assuming latest.
20:24:31 +0000 INFO: Downloading Puppet latest for Rocky...
20:24:31 +0000 CRIT: Sorry Rocky is not supported yet!
> (MODULES-11135) puppet_agent : Add task support for Rocky Linux 8.4 Green Obsidian

- Gemfile
- README.markdown
- acceptance/tests/test_upgrade_puppet5_to_puppet6.rb
- acceptance/tests/test_upgrade_puppet6_to_puppet7.rb
- lib/puppet/provider/puppet_agent_end_run/puppet_agent_end_run.rb
- manifests/init.pp
- manifests/install.pp
- manifests/install/suse.pp
- manifests/osfamily/suse.pp
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_spec.rb
- spec/spec_helper.rb
- spec/unit/puppet/provider/puppet_agent_end_run_spec.rb
This pull requests intends to implement the package versions `present` and `latest` as valid package versions. According to #333, this was the case prior to commit c2206a7. The issue with #333 is that it is an outdated pull request that does not apply to the current state of  `main`. This, along with the fact that the author of #333 did not agree to the CLA in over 2 years now, is why I am raising this as a separate pull request.
Since there is no issues section in this project, I would also like to use this pull request as a discussion for this feature. The issue with the implementation as it is proposed in this pull request is that every puppet run will end with:
```
Notice: Stopping run after puppet-agent upgrade. Run puppet agent -t or apply your manifest again to finish the …
```
> (MODULES-11113) Allow present and latest as package version

- tasks/install_shell.sh
we add this earlier for testing and it will be updated when the official image is released
> (MODULES-11060) Add Debian 11 testing support to install task

- manifests/install/windows.pp
- spec/classes/puppet_agent_windows_install_spec.rb
The install puppet command in `manifests/install/windows.pp` is executed if the desired version is not already installed. This is done by asking facter the value of the `aio_agent_version` fact on the target node and is compared to expected package version.
Before this commit, facter was asked to also load puppet facts (using the `-p` parameter) which was causing high load times due to unnecessary facts getting loaded and resolved when currently installed puppet agent version was the only information needed.
This fix removes the puppet facts loading for this command requirement and lowers catalog application time by as much as half in some scenarios. In our minimal and default environment we got the following output on a Windows node:
:x: Before fix:
```sh-session
➜ puppet agent -t …
```
> (MODULES-11123) Avoid loading puppet facts in `install/windows.pp`

- tasks/install_shell.sh
This PR add full support for FreeBSD.
If depends on this external PR:
* https://github.com/puppetlabs/puppetlabs-facts/pull/54
It is successfuly used for managing my configuration files on multiple operating systems:
https://github.com/smortex/dotfiles
> Allow detection of non-AIO Puppet

- docker/centos/Dockerfile
- docker/centos/Dockerfile.versions
The dockerfiles are only used for iterative development to test upgrades.
```
$ bundle update
...
$ docker/bin/upgrade.sh centos 6.25.1 7.13.1
Sending build context to Docker daemon  2.609MB
Step 1/28 : FROM centos:8
---> 5d0da3dc9764
Step 2/28 : RUN  yum update -y   && yum install -y wget git   && yum clean all
...
Notice: /Stage[main]/Puppet_agent::Install/Package[puppet-agent]/ensure: ensure changed '6.25.1-1.el7' to '7.13.1'
Debug: /Package[puppet-agent]: The container Class[Puppet_agent::Install] will propagate my refresh event
Notice: Stopping run after puppet-agent upgrade. Run puppet agent -t or apply your manifest again to finish the transaction.
Debug: Class[Puppet_agent::Install]: Transaction canceled, skipping
Debug: Class[Puppet_agent::Configure]: Transaction canceled, …
```
> (MODULES-11238) Bump centos base docker image

- acceptance/tests/test_upgrade_puppet6_to_puppet7.rb
- manifests/osfamily/darwin.pp
Previously, any Darwin 11 machine that used a facter version older than
4.1.1, and tried to update the puppet-agent version using the
puppetlabs-puppet_agent module, would recieve a badly generated URL.
This happened because the `productversion_major` fact also included the
minor version.
> (MODULES-11214) Wrong url generated for darwin 11

- acceptance/tests/test_upgrade_puppet5_to_puppet6.rb
- acceptance/tests/test_upgrade_puppet6_to_puppet7.rb
When we test upgrades we should only check to look for the major version.
We use to test the latest known puppet-agent package was upgraded. Due
to a bug in our puppet-agent packaging there are times this test would
produce a failure, even though the agent was upgraded to the major version.
> (MODULES-11262) Update the version check for acceptance check

- acceptance/Gemfile
GitHub deprecated the git network protocol in March 2022. However,
some of our tests are still attempting to clone down GitHub
repositories with the git protocol.
This commit changes the acceptance Gemfile to download
beaker-puppet over HTTPS instead of git.
> (maint) Adds HTTPS protocol to acceptance Gemfile

- .github/workflows/daily_unit_tests_with_nightly_puppet_gem.yaml
- .github/workflows/unit_tests_with_nightly_puppet_gem.yaml
- .github/workflows/unit_tests_with_released_puppet_gem.yaml
The Windows 2016 runner image went EOL on March 15, 2022
https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/
> (maint) Use windows-2022 runners

- manifests/init.pp
- spec/classes/puppet_agent_osfamily_aix_spec.rb
- spec/classes/puppet_agent_osfamily_darwin_spec.rb
- spec/classes/puppet_agent_osfamily_windows_spec.rb
- spec/classes/puppet_agent_spec.rb
puppet-agent 6.27.1 was release last month and contained Puppet version 6.27.0, a rare divergence between the puppet-agent version and the Puppet version. This discrepancy can cause issues using the puppet_agent _module_ when using the "auto" value for the `package_version` attribute.
> (MODULES-11315) Updates AIO auto version logic

- .github/workflows/auto_release.yml
Updates commit summaries to include the `(packaging)` prefix
to appease the static code analysis PR check.
Updates link to to nightly tests.
> (maint) Minor auto_release workflow fixes

- task_spec/spec/acceptance/init_spec.rb
Fedora 34, Debian 11, and Red Hat 9 were all added after the 6
series had been released. As a result, we need special cases
for them in our install task test.
> (maint) Adds cases for newly-supported OSes

- .rubocop.yml
- files/rb_task_helper.rb
- tasks/delete_local_filebucket.rb
- tasks/facts_diff.rb
- tasks/run.rb
This unnests module and class names in the Ruby tasks and the Ruby task
helper. Using a compact class declaration introduced a bug, as the
`PuppetAgent` class was not declared anywhere, which would result in the
Ruby tasks failing when run.
> (maint) Unnest module and class names in Ruby tasks

- acceptance/README.md
- task_spec/spec/acceptance/init_spec.rb
- tasks/install_shell.sh
Emit task output when something goes wrong to ease debugging,
Distinguish between macOS 12 x86_64 and ARM in tests and install task.
> (FM-8969) Add support for macOS 12 ARM

- tasks/install.json
- tasks/install_powershell.json
- tasks/install_powershell.ps1
- tasks/install_shell.json
- tasks/install_shell.sh
When using a synced Pulp repo against Puppets repositories (apt.puppet.com and yum.puppet.com); it's not possible to use the `yum_source` or the `apt_source` parameters; since the installer package is not available at the relative location which is constructed by the `puppet_agent::install` task.
This PR adds support for an `absolute_source` as parameter to the `puppet_agent::install` task.
> Add support for absolute_source in puppet_agent::install task

- task_spec/spec/acceptance/init_spec.rb
This updates the bolt task used to install puppet-agent for Fedora 36 and recently released OS'es.
On Fedora 36:
* Install 6.x nightly and upgrade to 7.x nightly.
* Skip 6.x -> 6.y updates since there's only one "latest" version
On macOS 12 x86_64:
* Enable 6.x -> 6.y upgrades since it's been supported for multiple 6.x releases.
On Ubuntu 22.04 and macOS 12 M1:
* Install 6.28.0 instead of nightly
* Continue to skip 6.x -> 6.y upgrades since we don't have immediate plans for 6.29.
> (FM-8983) Add Fedora 36

- spec/classes/puppet_agent_osfamily_debian_spec.rb
- tasks/install_shell.sh
Ubuntu 16.04 hit end-of-life in April 2021. This commit removes this version of Ubuntu from the installation task and tests.
> (MODULES-11328) Removes Ubuntu 16.04

- tasks/install_shell.sh
Debian 9 ("stretch") hit the end of its LTS support in June 2022 This commit removes Debian 9 (and older) from the installation task.
> (MODULES-11339) Removes Debian 9 from install task

- .github/workflows/task_acceptance_tests.yaml
- .github/workflows/unit_tests_with_nightly_puppet_gem.yaml
- .github/workflows/unit_tests_with_released_puppet_gem.yaml
The Ruby versions used in our GitHub Actions were inconsistent. This commit sets all Ruby versions to use the short version (e.g. 2.5 instead of 2.5.9) for all Rubies to automatically match the latest release of that version.
> (maint) Standardizes Rubies in GitHub Actions

- .github/workflows/daily_unit_tests_with_nightly_puppet_gem.yaml
- .github/workflows/unit_tests_with_nightly_puppet_gem.yaml
- .github/workflows/unit_tests_with_released_puppet_gem.yaml
- .gitignore
- .vscode/extensions.json
GitHub Actions' macOS 10.15 runners are going end-of-life on December 1, 2022:
https://github.com/actions/runner-images/issues/5583
This commit updates the macOS runners in use to macos-latest, which is currently macOS 11 Big Sur.
> (MODULES-11345) Updates macOS GitHub Actions runners 

- .github/workflows/daily_unit_tests_with_nightly_puppet_gem.yaml
- .github/workflows/static_code_analysis.yaml
- .github/workflows/task_acceptance_tests.yaml
- .github/workflows/unit_tests_with_nightly_puppet_gem.yaml
- .github/workflows/unit_tests_with_released_puppet_gem.yaml
- task_spec/spec/acceptance/nodesets/docker/ubuntu-20.04.yml
GitHub is deprecating Ubuntu 18.04 runners on April 1, 2023. This commit switches all Ubuntu 18.04 runners used in GitHub Actions to Ubuntu 20.04.
> (MODULES-11368) Update Ubuntu GitHub Action runner

- acceptance/tests/test_upgrade_puppet6_to_puppet7.rb
With the creation of the 7.x branch of puppet-agent we need to update the job to pull from that now.
> (maint) Update 6->7 to pull latest version from 7.x and not main branch

- manifests/install.pp
- spec/classes/puppet_agent_osfamily_debian_spec.rb
- spec/classes/puppet_agent_spec.rb
This commit replaces references to `lsbdistcodename` with `os.distro.codename`.
`lsbdistcodename` is a legacy fact that is used to determine the package name but
it requires the lsb-release package. Additionally, for Puppet 8, we are moving
towards dropping legacy facts. Also, since Facter 3+ provides the structured
fact, `os.distro.codename`, users can safely upgrade from Puppet 6/7 to 8 or from
Puppet 8.x to 8.y when using `os.distro.codename`. Due to these reasons, 
`os.distro.codename`, will be used instead of `lsbdistcodename`.
> (MODULES-11348) Replace lsbdistcodename with os.distro.codename

- .github/workflows/auto_release.yml
- .github/workflows/daily_unit_tests_with_nightly_puppet_gem.yaml
- .github/workflows/release.yml
- .github/workflows/static_code_analysis.yaml
- .github/workflows/task_acceptance_tests.yaml
- .github/workflows/unit_tests_with_nightly_puppet_gem.yaml
- .github/workflows/unit_tests_with_released_puppet_gem.yaml
This PR does some minor housekeeping for our GitHub Actions:
- Updates the checkout action in preparation for an upcoming NodeJS deprecation
- Updates the Ruby version for our static code analysis workflow to a version that's not end-of-life
> (maint) GitHub Actions housekeeping

- .fixtures.yml
- acceptance/helpers.rb
- manifests/init.pp
- manifests/install.pp
- manifests/install/solaris.pp
- manifests/install/suse.pp
- manifests/install/windows.pp
- manifests/osfamily/aix.pp
- manifests/osfamily/darwin.pp
- manifests/osfamily/redhat.pp
- manifests/osfamily/solaris.pp
- manifests/osfamily/suse.pp
- manifests/params.pp
- manifests/prepare.pp
- manifests/prepare/package.pp
- manifests/service.pp
- metadata.json
- spec/classes/puppet_agent_osfamily_aix_spec.rb
- spec/classes/puppet_agent_osfamily_darwin_spec.rb
- spec/classes/puppet_agent_osfamily_debian_spec.rb
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
- spec/classes/puppet_agent_osfamily_windows_spec.rb
- spec/classes/puppet_agent_params_spec.rb
- spec/classes/puppet_agent_spec.rb
- spec/classes/puppet_agent_windows_install_spec.rb
- spec/spec_helper_acceptance.rb
- spec/spec_helper_local.rb
In preparation for the removal of legacy facts in Puppet 8, this commit updates all of the legacy facts in this module to modern, structured facts.
> (MODULES-11361) Updates legacy facts

- manifests/init.pp
This replaces the validate_absolute_path() function call with a datatype from puppetlabs/stdlib. The type is available since the 4.13.1 release of stdlib (and this module already depends on 5.1 and newer).
Some background: I'm currently debugging a slow pe-puppetserver metrics API. The puppet-profiler is enabled and provides metrics for all called functions. In our environment the puppet_agent module is the only one still using this legacy function. By replacing it with a datatype, it follows current best practice guides and also speeds up the API because it has to care about less metrics (in my specific case at least).
> (maint) replace legacy validate function with datatype

- .fixtures.yml
- metadata.json
- spec/default_facts.yml
(MODULES-11346) Update dependency for APT module
Prior to this commit, the puppet_agent module requirements would put it at odds with other supported modules based on thee APT requirement of less than version 9.0
I also update the fixtures to that tests where carried out on the versions stated as supported in the metadata.yaml
> (MODULES-11346) Update dependency for APT module

- acceptance/Rakefile
- acceptance/helpers.rb
- acceptance/pre_suite/00_master_setup.rb
- acceptance/tests/test_upgrade_puppet7_to_puppet8.rb
- spec/spec_helper_acceptance.rb
This commit adds a Beaker test for upgrading from Puppet 7 to Puppet 8.
> (MODULES-11392) Add Puppet 7 to 8 upgrade test

- .github/workflows/unit_tests_with_nightly_puppet_gem.yaml
- .sync.yml
- Gemfile
- spec/classes/puppet_agent_osfamily_aix_spec.rb
- spec/classes/puppet_agent_osfamily_darwin_spec.rb
- spec/classes/puppet_agent_osfamily_debian_spec.rb
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
This PR fixes an issue with rspec tests not using keyword arguments with the `override_facts` helper method, which causes issues with later versions of Ruby as keyword argument behavior changes from Ruby >= 3.
This PR also replaces puppet5 tests with nightly gems with puppet8 on Ruby 3.2. 
I tested these commits locally by running `bundle exec rake parallel_spec` on both Ruby 2.7.7 and Ruby 3.2.1.
> (MODULES-11365) Enable rspec tests on Ruby 3.2

- .sync.yml
- HISTORY.md
- Rakefile
When attempting to run the auto_release Action to prep for our next release, we encountered a few issues with the GitHub Changelog Generator. This PR comprises commits that reduce the amount of history, PRs, and issues that GHCLG have to look through to generate a changelog for the upcoming release.
See Slack for more context: https://perforce.slack.com/archives/C049PL6AUCU/p1679344230633679
> (maint) Prerelease fixes

- .sync.yml
- Gemfile
In 99d7dcb we pinned Octokit to 4.21.0 due to an issue with authentication and the Faraday gem in Octokit 4.22.0. There was a fix for this issue in 4.23.0, so we no longer need to pin back.
This gem is used to generate changelogs in release prep, and other modules (i.e. Puppet core modules) have used newer versions of Octokit (4.25.0) without issue.
This commit removes the pin for Octokit to 4.21.0.
> (maint) Unpin Octokit gem

- acceptance/helpers.rb
- acceptance/pre_suite/00_master_setup.rb
Nightlies for puppetserver 8 have started to ship as of yesterday.
This commit enables the puppet7 to puppet8 upgrade test to use puppetserver 8 nightlies.
> (maint) Enable puppetserver 8 nightlies

- .github/workflows/task_acceptance_tests.yaml
- acceptance/tests/test_upgrade_puppet7_to_puppet8.rb
- task_spec/spec/acceptance/init_spec.rb
- tasks/install.json
- tasks/install_powershell.json
- tasks/install_shell.json
This commit updates acceptance tests and tasks for the puppet8 final release. Previously, these things only accounted for the nightly releases.
> (PA-5336) Update tests and tasks for puppet8

- .sync.yml
- HISTORY.md
- Rakefile
This PR comprises changes necessary for GitHub Changelog Generator to not get rate-limited by GitHub (as seen [here](https://github.com/puppetlabs/puppetlabs-puppet_agent/actions/runs/4823900586/jobs/8592997755)) when attempting to iterate through this repository's pull requests and issues.
> (maint) Release prep

- manifests/params.pp
- spec/classes/puppet_agent_params_spec.rb
This commit adds mappings for Puppet Enterprise 2023.3 to puppet8.
> (PA-5337) PE integration

- .fixtures.yml
- manifests/params.pp
- metadata.json
- spec/classes/puppet_agent_osfamily_aix_spec.rb
- spec/classes/puppet_agent_osfamily_darwin_spec.rb
- spec/classes/puppet_agent_osfamily_debian_spec.rb
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_osfamily_solaris_spec.rb
- spec/classes/puppet_agent_osfamily_suse_spec.rb
- spec/classes/puppet_agent_osfamily_windows_spec.rb
- spec/classes/puppet_agent_spec.rb
- spec/classes/puppet_agent_windows_install_spec.rb
stdlib 9 dropped the `is_function_available()` function. I reworked the code to check if `pe_anchor` is defined. The code now works with Puppet core functions and is compatible with Puppet 7/8, probably 6, and does not rely on stdlib.
> Implement stdlib 9 compatibility

- manifests/init.pp
- spec/acceptance/class_spec.rb
- spec/classes/puppet_agent_osfamily_windows_spec.rb
- spec/spec_helper_acceptance.rb
Windows requires the current puppet collection to be specified in the puppet_agent class, so that is refactored to be globally specified in the `spec_helper_acceptance`. Additionally, logic was added to specifiy default install paths for the VERSION file for both linux and windows.
> (maint) Make spec tests pass on windows

- manifests/osfamily/aix.pp
- spec/classes/puppet_agent_osfamily_aix_spec.rb
Drop puppet5/PE 2018.x support for AIX
AIX 7.1 is not supported in puppet8 and will be removed from puppet7 in the near future.
> (PA-5721) Add puppet8 and drop puppet5 support from AIX

- rakelib/commits.rake
Currently, the "Static Code Analysis / Run checks" will fail on release prep PRs because the check does not include "Release prep". This commit updates the commits Rake task to check for "Release prep" in the PR title/name.
> (maint) Update commits.rake to check for "Release prep"

- manifests/prepare/package.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
Prior to this commit, the puppet_agent::prepare::package class used the sha256lite algorithm in the file resource for local installation packages.
In certain circumstances (e.g. when a download is interrupted), this checksum, which only checks the first N bytes, does not provide sufficient information to determine if the file is actually there.
This commit updates the file resource to use the more complete sha256 algorithm to handle cases like this.
> (PA-5266) Change checksum algorithm to SHA256 

- REFERENCE.md
- manifests/init.pp
- manifests/install.pp
- manifests/install/darwin.pp
- manifests/install/solaris.pp
- manifests/install/suse.pp
- manifests/prepare/package.pp
- manifests/prepare/puppet_config.pp
As part of 404df9d all parameters in this module were assigned a data type. However, some required parameters were mistakenly classed as Optional and vice-versa.
Puppet's documentation states "If a class parameter lacks a default value, the parameter is considered required."[1]
This commit updates all parameters with default values to Optional (and whatever other relevant data type) and all parameters without default value as required. The REFERENCE.md has been updated to reflect these changes.
Additionally, this commit updates all Optional parameters be set as undef, as suggested by the optional_default puppet-lint check.
[1] https://www.puppet.com/docs/puppet/7/lang_classes#class-parameters-and-variables
> (maint) Update optional parameters

- REFERENCE.md
- manifests/init.pp
In PR #663 an overly strict datatype was set for the skip_if_unavailable parameter. The yumrepo type supports a variety of string values and boolean values.
> Match allowed datatypes to yumrepo skip_if_unavailable support

- REFERENCE.md
- manifests/install.pp
- manifests/install/darwin.pp
- manifests/install/solaris.pp
- manifests/install/suse.pp
- manifests/install/windows.pp
Previously, 74e022d erroneously typed the $package_version and $install_options parameters as Optional.
This commit updates those parameters to be required, and gives a more specific type to $install_options.
> (PA-5820) Correct parameter types

- .github/workflows/static_code_analysis.yaml
- .github/workflows/task_acceptance_tests.yaml
The Checkout GitHub Action v3 uses Node 16, which hit end-of-life on September 11, 2023.
This commit updates all instances of the Checkout Action from v3 to v4.
> (PA-5792) Update Checkout GitHub Action

- task_spec/spec/acceptance/init_spec.rb
Below is the output generated by my test
```bash
install task
Installed puppet-agent on ip-10-227-6-48.amz-dev.puppet.net: success
Ensuring installed puppet-agent on ip-10-227-6-48.amz-dev.puppet.net: success
Upgraded puppet-agent to latest puppet7 on ip-10-227-6-48.amz-dev.puppet.net: success
Upgraded puppet-agent to puppet8 on ip-10-227-6-48.amz-dev.puppet.net: success
works with version and install tasks
Finished in 3 minutes 52.5 seconds (files took 2 minutes 2.7 seconds to load)
1 example, 0 failures
```
> (PA-5065) Add Ubuntu 22.04 (ARM64) to the puppet_agent module

- REFERENCE.md
- lib/facter/puppet_runmode.rb
- manifests/init.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- spec/classes/puppet_agent_osfamily_windows_spec.rb
Previously, puppetserver attempted to load the wrong VERSION file when managing `package_version => auto` and compiling catalogs for Windows nodes as can be seen by the new test:
Evaluation Error: Error while evaluating a Function Call, Could not find any files from C:\Program Files\Puppet Labs\Puppet\VERSION (file: path/to/init.pp, line: 170, column: 42)
This adds a `puppet_runmode` fact. When running as puppet agent, the run mode will be `agent`. When running as puppet apply, it will be `user`. If it's the latter and we're a Windows host, then look for the VERSION file locally.
> (PA-5826) Only read Windows VERSION file during puppet apply

- .github/workflows/jira.yml
- metadata.json
This PR:
- Updates the issues URL in metadata.json from Puppet's old Jira instance to GitHub Issues.
- Adds a workflow to export GitHub issues to Puppet's internal-only Jira instance.
> (PA-5395) Issues housekeeping

- .fixtures.yml
This is how we run unit tests on Vox Pupuli modules. This was already done for puppetlabs-stdlib in #657.
This also removes the unused and deprecated translate module.
> .fixtures.yml: test with the main branches of modules

- spec/classes/puppet_agent_osfamily_debian_spec.rb
- tasks/install_shell.sh
Public nighty builds are currently available and working if component is puppet8-nightly or puppet7-nightly.
> Add Debian 12 bookworm support

- acceptance/Gemfile
If BEAKER_PUPPET_VERSION is not defined, then bundle install will fail, because this module is still using beaker 4, but the head of beaker-puppet requires beaker 5.
This module is not yet beaker 5 compatible, so pin to an earlier beaker-puppet.
> Pin to beaker-puppet 2.x by default

- tasks/install_shell.sh
minimal OS installs without wget or curl may not have perl LWP::Simple either, but perl File::Fetch is often available.
> support download with perl file::fetch

- tasks/install_shell.sh
Found minimal images that do not include perl, curl, or wget, but did have python3.
urllib.request is built-in to python3, reliable way to download for our purposes.
> support download with python3 urllib.request

- tasks/install_shell.sh
Fixes #703 by using the `type` shell builtin instead of the (maybe not installed) `which` binary.
> [Fix #703] use 'type' instead of 'which' for increased portability

- task_spec/spec/acceptance/init_spec.rb
Added debian-12 to the puppet agent module task acceptance
> [PA-5586]: Add debian-12-x86_64 to the puppet agent module task acceptance

- manifests/osfamily/suse.pp
- spec/classes/puppet_agent_osfamily_suse_spec.rb
This PR adds a GPG check to SUSE repos created by this module. This mirrors behavior already found in public release packages (see https://github.com/puppetlabs/puppetlabs-release/blob/main/source/yum.puppet.com/puppet-release.sles.template#L6) and the pe_repo module.
I tested this on SLES 12: 
```
leaky-toolmaker:~ # /opt/puppetlabs/puppet/bin/puppet --version
7.28.0
leaky-toolmaker:~ # cat /etc/zypp/repos.d/pc_repo.repo
[pc_repo]
name = pc_repo
enabled = 1
gpgcheck = 1
autorefresh = 0
baseurl = http://yum.puppet.com/sles/12/PC1/x86_64?ssl_verify=no
type = rpm-md
leaky-toolmaker:~ # cat test.pp
class { '::puppet_agent':
package_version => '7.29.1',
}
leaky-toolmaker:~ # /opt/puppetlabs/bin/puppet apply test.pp
Notice: Compiled catalog for leaky-toolmaker.delivery.puppetlabs.net in …
```
> Add GPG check to SUSE repository

- task_spec/spec/acceptance/init_spec.rb
```bash
install task
Installed puppet-agent on ip-10-227-4-74.amz-dev.puppet.net: success
Ensuring installed puppet-agent on ip-10-227-4-74.amz-dev.puppet.net: success
Upgraded puppet-agent to latest puppet7 on ip-10-227-4-74.amz-dev.puppet.net: success
Upgraded puppet-agent to puppet8 on ip-10-227-4-74.amz-dev.puppet.net: success
works with version and install tasks
Finished in 2 minutes 42.1 seconds (files took 1 minute 28.17 seconds to load)
1 example, 0 failures
> (PA-5318) Add Debian 11 (ARM) to the puppet_agent module task acceptance

- manifests/install/windows.pp
When running on Puppet 8, a warning is produced:
```
The argument signature (String format, [String timezone]) is deprecated for #strftime. See #strftime documentation and Timespan type for more info
```
Pass a timestamp as the first parameter to use a non-deprecated
signature of the function `(Timespan $time_object, String $format)`.
> Fix strftime() deprecation warning

- tasks/run.rb
previously we assumed that an environment exists in the params hash. And we didn't allow environment names with a single character. This PR fixes both.
> puppet_agent::run: properly validate environment parameter

- tasks/install_shell.sh
observed the latest rockylinux 9 containers do not have a yum symlink to dnf anymore.
Related:
* https://github.com/puppetlabs/provision/pull/261
* https://github.com/puppetlabs/litmusimage/pull/88
> Support rpm platforms without yum

- manifests/osfamily/redhat.pp
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
Since we currently use the Amazon repository for Amazon Linux on the Yum repo instead of `el`, we are changing the manifest to fetch the correct package.
> (PA-6277) change manifests for amazon 2 repo

- manifests/osfamily/redhat.pp
- metadata.json
- spec/classes/puppet_agent_osfamily_redhat_spec.rb
- tasks/install_shell.sh
Previous commits fixed AL2 aarch64, but broke x86_64.
Added `AmazonLinux` to metadata.json
After this is merged, install-puppet.sh needs to be regenerated
This should fix https://jenkins-enterprise.delivery.puppetlabs.net/view/pe-integration/view/pe-2021.7.x/job/enterprise_pe-acceptance-tests_integration-system_pe_full-agent-upgrade_nightly_2021.7.x/
> (PA-6677) Restore AL2 x86_64 install task and manifest

- task_spec/spec/acceptance/init_spec.rb
Added fedora-40 to 'latest_platform_list' method so that it considers builds from nightlies with the 'latest' tag since the versioned release package won't be available for fedora-40 yet given its a new platform we're just introducing. 
Also set 'multiple_puppet7_version' to false for the case of fedora-40 because we would only have just one puppet7 release initially.
> (PA-6367) Update task_acceptance for Fedora 40 x86_64

- acceptance/helpers.rb
- manifests/osfamily/debian.pp
- metadata.json
- spec/classes/puppet_agent_osfamily_debian_spec.rb
- spec/spec_helper_acceptance.rb
This updates `puppet_agent::osfamily::debian` to use modern APT keyrings (https://github.com/puppetlabs/puppetlabs-apt/pull/1128) instead of the deprecated `apt-key` method used by `apt::key` and `apt::source.key` without `name`.
For this to work properly, it needs a release of puppetlabs-apt which contains https://github.com/puppetlabs/puppetlabs-apt/pull/1128, which should be the release after v9.1.0.
This also removes the legacy key, because keys not used for signing package sources aren't needed.
`/etc/pki` is not needed anymore (also this directory is a RedHatism) because keyrings are now stored in the default location of `/etc/apt/keyrings`. We don't clean it up though, in case people are using the files there for something else.
> (MODULES-9695) Debian: use modern APT keyring format

- tasks/install_shell.sh
- tasks/version_shell.sh
This ensures that the task doesn't continue when an error happened. This is also best practice in bash.
> sh tasks: Run with set -e

- tasks/install_shell.sh
recent ubuntu official docker images are unable to download with any of the other methods
> install support download with apt-helper

- task_spec/spec/acceptance/init_spec.rb
After https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/711 was merged, it revealed a test failure with Fedora 40 relating to our test setup.
This PR updates our tests to use the correct versions of puppet-agent for Fedora 40 and Ubuntu 24.04.
> Test updates

- Gemfile
- manifests/osfamily/debian.pp
- spec/classes/puppet_agent_osfamily_debian_spec.rb
for the changes in https://github.com/puppetlabs/puppetlabs-apt/commit/1e1baadf8158a878562b8aab1924a3db5b777a0c#diff-792ade83ea45b5c6696875678e6e7cc52f4a105db6ed4d8b6f2933ec5d7d6f3bR25-R26
see also https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/738#issuecomment-2489350309
> Adopt to latest puppetlabs/apt changes

- .sync.yml
- Gemfile
The 0.7.1 release of orchestrator_client broadened its dependency on Faraday (see puppetlabs/orchestrator_client-ruby@6f8661e). This change has caused Bundler to resolve Faraday in unexpected ways when there are other Gems with dependencies on Faraday.
This commit constrains orchestrator_client to < 0.7.1 until this issue is resolved.
> Constrain orchestrator_client

- tasks/run.rb
* This is an alternative to https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/741
* this contains #739 
without this change:
```
Started on localhost...
Finished on localhost:
Info: Refreshing CA certificate
Info: CA certificate is unmodified, using existing CA certificate
Info: Using environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Notice: Requesting catalog from puppet.bastel:8140 (127.0.0.1)
Notice: Catalog compiled by puppet.local
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Failed when searching for node puppet.bastel: Exception while executing '/etc/puppetlabs/puppet/node.rb': Cannot run program "/etc/puppetlabs/puppet/node.rb" (in directory "."): error=0, Failed to exec spawn …
```
> (#732) puppet_agent::run: mark failed puppet runs as failed task

- tasks/run.rb
By default, `Puppet::Util::Execution.execute` only returns stdout. Puppet writes errors to stderr. When the run task fails, it only shows the successful output:
```
$ bolt task run puppet_agent::run --targets puppet
Started on puppet...
Finished on puppet:
Info: Using environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Notice: Requesting catalog from puppet.local:8140 (10.0.1.1)
Notice: Catalog compiled by puppet.local
*long json here*
```
With the patch:
```
$ bolt task run puppet_agent::run --targets puppet
Started on puppet...
Finished on puppet:
Info: Using environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Notice: Requesting catalog from puppet.local:8140 (10.0.1.1)
Notice: Catalog compiled …
```
> (#732) run.rb: Combine stderr and stdout

- acceptance/tests/test_upgrade_puppet6_to_puppet7.rb
- acceptance/tests/test_upgrade_puppet7_to_puppet8.rb
These tests already rely on internal infrastructure, so changing the nightly URLs shouldn't break anyone.
[update 6 -> 7: passed](https://jenkins-platform.delivery.puppetlabs.net/job/forge-module_puppetlabs-puppet-agent-module_intn-sys_pa-acceptance_6-nightly_to_7-nightly-adhoc/93/)
[update 7 -> 8: passed](https://jenkins-platform.delivery.puppetlabs.net/job/forge-module_puppetlabs-puppet-agent-module_intn-sys_pa-acceptance_7-nightly_to_8-nightly-adhoc/54/)
The tests didn't pass on macOS 12 ARM, because we aren't building packages for that anymore, so filed related PR https://github.com/puppetlabs/ci-job-configs/pull/9800
> Update nightly repos for beaker tests

- metadata.json
since https://github.com/puppetlabs/puppetlabs-apt/pull/1208, version 10 of puppetlabs/apt is required.
> puppetlabs/apt: Require 10.x

- task_spec/spec/acceptance/init_spec.rb
- tasks/install_shell.sh
For MacOS 15(ARM) - 
With this PR we are trying to only install puppet8. The upgrade part we will cover with another jira.
We don't support puppet7 for MacOS 15(ARM). So we don't need tests to upgrade the agent from puppet7 to puppet 8.
> (PA-6760) Update task_acceptance tests for MacOS15 ARM

- task_spec/spec/acceptance/init_spec.rb
- tasks/install_shell.sh
Modules that rely on litmus use the puppet_agent module to install the latest
released and nightly versions of `puppet-agent` packages:
bundle exec rake 'litmus:install_agent[puppet7-nightly]'
Commits https://github.com/puppetlabs/puppetlabs-puppet_agent/commit/025aa705f2f72d89cd7ea0daf3f51f71522d6c70 and https://github.com/puppetlabs/puppetlabs-puppet_agent/commit/b2e73a87867738204e83b42df6fa02f29f379d47 changed the default location where nightly
builds are installed from. Since we haven't documented how to do that, revert
those changes. Instead specify the internal sources in the test for the
situation where a platform has been recently added, but hasn't been released
yet, for example, macOS 15 ARM.
We will need to revisit how to install `puppet*_nightly` puppet core builds.
Fixes #758 …
> Install latest builds from internal nightlies in beaker tests

- tasks/install_shell.sh
Commit e6f817cba5057870c29b9dd220a048914d0c33a7 introduced a breaking change when downloading the GPG key from non-core repos on SLES.
It also incorrectly attempted to manage credentials for non-core repos for all rpm-based platforms.
This commit restores the GPG location on yum.puppet.com and guards the sed commands to only run when the repo collection contains "core"
This should fix https://jenkins-platform.delivery.puppetlabs.net/view/puppet-agent/view/Acceptance%20Suites/view/CI%20Goalie/job/forge-module_puppetlabs-puppet-agent-module_intn-run_task_acceptance-main/591/
> Fix breaking changes in non-core repos

- docker/bin/helpers/run-upgrade.sh
- manifests/osfamily/redhat.pp
- manifests/osfamily/suse.pp
An earlier version of PR #757 assumed the default yum_source was changing to yum-puppetcore.puppet.com. Later we decided not to introduce a breaking change and instead use puppetcore* collections to opt-into the new behavior. However, the PR wasn't updated to account for that. And I didn't notice the problem because the docker upgrade script was using the puppet8 collection.
Change the upgrade script to use puppetcore* collections and update the redhat and suse classes to install from yum-puppetcore.puppet.com when using the core repos.
❯ export PUPPET_FORGE_TOKEN=...
❯ docker/bin/upgrade.sh rocky 7.34.0 8.11.0
...
Notice: /Stage[main]/Puppet_agent::Install/Package[puppet-agent]/ensure: ensure changed '7.34.0-1.el8' to '8.11.0'
❯ docker/bin/upgrade.sh sles 7.34.0 8.11.0
...
Notice: …
> Fix rpm upgrades to puppetcore

- .github/workflows/task_acceptance_tests.yaml
- manifests/osfamily/debian.pp
The ubuntu 20.04 GitHub runner is deprecated and will be dropped April 1, so use latest.
The other ubuntu 20.04 instance is used to provision a docker container, so leave that as is.
Also appease puppet-lint.
> Use ubuntu-latest instead of 20.04

- task_spec/spec/acceptance/init_spec.rb
This commit adds Amazon FIPS 2023 (x86_64) support to task acceptance tests. Support for puppet7 to puppet8 upgrade tests has not been added since puppet7 is EOL and its packages were not built for the platform.
> (PA-7222) Add Amazon FIPS 2023 (x86_64) support in task acceptance tests

- REFERENCE.md
- manifests/init.pp
- manifests/osfamily/windows.pp
- manifests/prepare/package.pp
- metadata.json
- tasks/install_powershell.json
- tasks/install_powershell.ps1
- tasks/install_shell.json
- templates/download_puppet.ps1.epp
This is analogous to https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/757 but for windows.
Updates the `puppet_agent::install_task` so it's possible to install msi-based packages from https://artifacts-puppetcore.puppet.com. Credentials are required when installing from puppetcore. The username defaults to `forge-key` and the password must be set to your forge API token.
When using WinRM, you must specify Windows credentials (using `--user` and `--password` arguments) to log into the host and puppetcore credentials to download the MSI (as `username` and `password` task parameters)
```
$ /opt/puppetlabs/bolt/bin/bolt task run puppet_agent::install \
collection=puppetcore8 \
version=8.11.0 \
username=forge-key \
password=... \
--targets 'winrm://HOST' \
--user Administrator \ …
```
> Update module to support puppetcore on Windows

- tasks/install.json
- tasks/install_powershell.json
- tasks/install_shell.json
This commit marks `password` as sensitive in the install.json bolt task param metadata.
This prevents password from being shown in plaintext, in the bolt logs.
before:
```
Running task puppet_agent::install with '{"retry":5,"collection":"puppetcore8","version":"latest","password":"1234","_task":"puppet_agent::install"}' on [".."]
```
after:
```
Running task puppet_agent::install with '{"retry":5,"collection":"puppetcore8","version":"latest","password":"Sensitive [value redacted]","_task":"puppet_agent::install"}' on [".."]
```
> bug: mark password as sensitive in puppet_agent::install task

- manifests/osfamily/darwin.pp
- manifests/prepare/package.pp
- tasks/install_shell.sh
- templates/download_puppet.sh.epp
Adds support for installing puppetcore packages on macOS via bolt task:
```shell
/opt/puppetlabs/bolt/bin/bolt task run puppet_agent::install \
collection=puppetcore8 \
version=8.13.1 \
username=forge-key \
password=${PUPPET_FORGE_TOKEN} \
--targets 'www.example.com'
```
And upgrading installed packages to puppetcore over time:
```ruby
class { 'puppet_agent':
package_version => '8.13.1',
collection      => 'puppetcore8',
username        => 'forge-key',
password        => Sensitive(...)
}
include 'puppet_agent'
```
> Add puppetcore support for macOS

- .github/workflows/task_acceptance_tests.yaml
- task_spec/spec/acceptance/init_spec.rb
Previously, the puppet_agent::install task to install or upgrade to puppet8 used puppet8 builds from downloads.puppet.com. Since puppet8 builds are no longer published there, this commit updates the puppet_agent::install task to install or upgrade to puppet8 using the puppet8 dev builds from Artifactory instead.
This commit also adds some logger.info statements so it's easier to track what specific version of puppet-agent is being upgraded to or installed. Also, it adds a step in the task acceptance tests workflow to connect to Twingate so that workflow can access Artifactory.
> (PA-7433) Update task_spec to upgrade from puppet7 to latest puppet8 dev build

- .github/workflows/task_acceptance_tests.yaml
In the Task Acceptance Tests workflow, Twingate was having trouble connecting to Artifactory due to running the job in Docker containers. The Docker containers used in the workflow run on Azure VM's and Microsoft adds their own nameservers, 168.63.129.16. It gets copied to resolv.conf and interferes with Twingate which caused DNS resolution failures with Artifactory.
To resolve this, this commit adds a "Fix DNS" step that removes the Azure DNS name server and adds Twingate's DNS server.
>  (ITHELP-116185) Add fix dns step to Task Acceptance Tests workflow

- .github/workflows/static_code_analysis.yaml
The workflow was failing during bundle install because the secret PUPPET_FORGE_TOKEN wasn't passed:
/opt/hostedtoolcache/Ruby/3.1.7/x64/bin/bundle lock
Fetching source index from https://rubygems-puppetcore.puppet.com/
Bad username or password for https://forge-key@rubygems-puppetcore.puppet.com/.
> Pass credentials to reusable workflow
